<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SubmitJawaban</name>
   <tag></tag>
   <elementGuidId>0fe8a749-e5b9-47e8-8f5c-6bd872545a1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'SubmitJawaban']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SubmitJawaban</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#SubmitJawaban</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a733d136-49ec-47a5-9b90-394cf05fc092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>cc92d59b-1fe0-450b-822a-01dc0e9d1fa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>da5c4fcd-a4c1-478f-a571-05bd476cfc23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SubmitJawaban</value>
      <webElementGuid>bab1097c-76af-4f78-b493-0adcd166332e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Submit
                            </value>
      <webElementGuid>84736542-07b5-4e42-9f96-853d5f082460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-86d32d1f1503180096f6548c0fbe5662</value>
      <webElementGuid>69042831-735f-4db3-a04a-b97c0dda242c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'SubmitJawaban']</value>
      <webElementGuid>bbba0eab-5e64-40e0-a4cd-2d247337f443</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'SubmitJawaban']</value>
      <webElementGuid>2777e6e4-2ac2-4cbf-98ed-6cef920d995a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'SubmitJawaban' and (text() = '
                                Submit
                            ' or . = '
                                Submit
                            ')]</value>
      <webElementGuid>13942ac2-6a12-4e5d-ba74-4cb4f98523da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
