<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_txtNamaSearchParam</name>
   <tag></tag>
   <elementGuidId>82dcdacc-2d10-415c-9be7-8d779b3c5747</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'txtNamaSearchParam']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtNamaSearchParam</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtNamaSearchParam</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>26a36e7d-7721-4e3c-8a02-00c8b16b9acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f35a0c6f-35dd-4a41-9ccd-622a72f8797f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>660dc2e4-824b-4d4d-9167-f33e800cfcfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtNamaSearchParam</value>
      <webElementGuid>ea96d0ad-9cd6-4192-8c1d-10ca269ed40b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-111763c618ea82a11dcc008c9cf1b214</value>
      <webElementGuid>b0c532da-9887-4fce-81a7-685d157dbb70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'txtNamaSearchParam']</value>
      <webElementGuid>8a7a4689-da56-4e75-a9ec-61afa4d3fcc5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'txtNamaSearchParam']</value>
      <webElementGuid>bfc8acd5-79ed-465d-baef-25710c7295b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtNamaSearchParam']</value>
      <webElementGuid>709700be-fa65-4315-9b1a-443bd0dd615d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
