<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_btn-formkualitatif</name>
   <tag></tag>
   <elementGuidId>deff1514-9ee9-4e20-9037-556a8294b8a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-formkualitatif</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'btn-formkualitatif']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Review SIMON Kualitatif&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f90f0689-58e2-496f-aaa8-0a6051b5837b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>c456019b-f082-45a9-bd56-89d76fa1c6c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>55161b3b-cea4-4179-af66-5519b5a85b25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-formkualitatif</value>
      <webElementGuid>1e7ede28-a3e5-4b5c-9e3b-b03fcb43e16f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>138812</value>
      <webElementGuid>5d530652-d22d-4109-a241-15998d885f6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-segmen</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>87fabc7a-831c-473c-92f4-35ef90f279b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Review SIMON Kualitatif</value>
      <webElementGuid>733a6925-083d-4a4d-973c-c9dbd5234b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-37354bbaa94d8c0eceb1a7938111bc53</value>
      <webElementGuid>1ef2504e-197a-4227-8db3-56708e312981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'btn-formkualitatif']</value>
      <webElementGuid>1b274f3a-d09d-46c7-90a9-d1803c820375</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'btn-formkualitatif']</value>
      <webElementGuid>cfc3ad1b-0394-4eb2-9e5d-a5d73330a15c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'btn-formkualitatif' and (text() = 'Review SIMON Kualitatif' or . = 'Review SIMON Kualitatif')]</value>
      <webElementGuid>5795f28c-edfe-4455-a71f-8ad9da5c1d0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
