<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_nav-profile-img mr-2</name>
   <tag></tag>
   <elementGuidId>9c56c7f8-1927-433b-a7eb-bd3831e5611e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.nav-profile-img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' nav-profile-img ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>72d24502-482f-478c-889b-ebe8ce24ff20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-profile-img mr-2</value>
      <webElementGuid>694787f6-465a-4df6-8e86-2453b3cbaa1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/lib/breeze/images/faces/face1.jpg</value>
      <webElementGuid>2a9238b9-cc12-4c18-8e83-b5b6617f53e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-fdcbff016c3d454902534ea3828cb850</value>
      <webElementGuid>e2d349e4-196d-4a87-9ff5-ff73c7c51d80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' nav-profile-img ')]</value>
      <webElementGuid>adde5f0a-5ef7-49df-830d-323fb17f2ed3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' nav-profile-img ')]</value>
      <webElementGuid>3ec6aa8e-8af3-4978-9a5f-9f4dfc6337e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/lib/breeze/images/faces/face1.jpg']</value>
      <webElementGuid>1926eb30-a1f3-446c-8136-7fde732c8e46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
