<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_txtCifSearchParam</name>
   <tag></tag>
   <elementGuidId>8240b55d-775a-4ca3-9ba7-76732018fe2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtCifSearchParam</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'txtCifSearchParam']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtCifSearchParam</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e1550c53-4168-4eb4-ba73-8331639b2f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9c56392a-50db-4cfc-bea3-b56bba8eda17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>46e623c5-efe7-425f-850a-97cd0fc62e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtCifSearchParam</value>
      <webElementGuid>17f9f08f-b314-4952-bfa7-0b21348fe4fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-4acac71bfbc0c93a351a35a50050b2c1</value>
      <webElementGuid>158b9deb-7fc1-4598-9858-62c4cc1679c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'txtCifSearchParam']</value>
      <webElementGuid>126b4a5d-89ab-452c-97bc-5d0e9079d3a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'txtCifSearchParam']</value>
      <webElementGuid>bf25c4b5-f132-47b2-889d-b26a30e99d2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtCifSearchParam']</value>
      <webElementGuid>3ddaa578-b4cf-49aa-b5bd-837fc6ce5b84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
