<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Type your text here</name>
   <tag></tag>
   <elementGuidId>d69543bd-e47c-4bfc-9ecd-2965ad523502</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#komentar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'komentar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Type your text here&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>02a49717-1048-4313-828b-ff452059753d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>komentar</value>
      <webElementGuid>1c9e23e8-e7a3-4dc2-8d3c-3644acd7d451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e4c550b6-c2c8-4ac6-8f1b-90b9858bf2df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>453b61f0-f7c9-4c1a-a8e7-2db1c20cd47f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type your text here</value>
      <webElementGuid>d1245924-1ed6-450b-b35b-aacdfc99c7c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-8c3a05648b85baa9ede3b0b7754c9481</value>
      <webElementGuid>2ec6662b-c8c3-4294-a9c4-1af731aad7c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'komentar']</value>
      <webElementGuid>ee93b859-b61e-4b3a-8696-700d20c9dcf4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'komentar']</value>
      <webElementGuid>dcdb9439-8e4e-40a5-a7a9-4b845dd5c3c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'komentar' and @placeholder = 'Type your text here']</value>
      <webElementGuid>8a3ee992-1eda-4dfb-8037-dc0f18e3b491</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
