<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SIMON - Test Suite (Upload Data SME)</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>eac48849-d32d-4528-8d3f-288c9e8fe873</testSuiteGuid>
   <testCaseLink>
      <guid>2b3a52e2-67df-4dc2-b853-c0bb0613b14f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <iterationNameVariable>
         <defaultValue>'admin'</defaultValue>
         <description></description>
         <id>645b335f-eed9-48af-9a2f-cde5e6941ca2</id>
         <masked>false</masked>
         <name>username</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/Authentication/SIMON - Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>972093be-0ea6-48a7-8a89-9b7c49734887</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Admin Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>972093be-0ea6-48a7-8a89-9b7c49734887</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>645b335f-eed9-48af-9a2f-cde5e6941ca2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4d124ae0-04cd-416e-a0af-7f58aa51b2c6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Upload Data SIMON/SIMON - Upload SME</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4ab2daba-0f6b-4e6b-a464-e745f91939cc</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/SME Hijau File Path</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>4ab2daba-0f6b-4e6b-a464-e745f91939cc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>filePath</value>
         <variableId>8c6e5224-7d69-4202-baba-dcfb33b49b9b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8b56cbd1-7b81-47df-9f63-a2b6c396637c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Authentication/SIMON - Log Out</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>e0af3079-d21e-403f-88e5-291b74091f83</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Authentication/SIMON - Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4282e295-ce69-460b-b278-f89878a94e5a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Inputter SME NPP</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>4282e295-ce69-460b-b278-f89878a94e5a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>645b335f-eed9-48af-9a2f-cde5e6941ca2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7128c398-e978-407e-8e5c-d3bfc1b8db83</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Inputter Progress/SIMON - Inputter SME</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>2436157b-96a4-408b-b0ed-4a6a203d2cde</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/SME Hijau CIF</testDataId>
      </testDataLink>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>1ecd3a19-f193-44a2-bfc5-659b2c3065c2</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Dummy File Path</testDataId>
      </testDataLink>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>ac46517c-c473-44b7-8c6c-3de4ff448732</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Hijau Conditional Variable</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>2436157b-96a4-408b-b0ed-4a6a203d2cde</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>cif</value>
         <variableId>1115a7e4-4a7c-4b36-906c-b70713b00dad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1ecd3a19-f193-44a2-bfc5-659b2c3065c2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>filePath</value>
         <variableId>bf88a66c-7f5e-404b-bd71-0bbf2e08f76f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ac46517c-c473-44b7-8c6c-3de4ff448732</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>hijau</value>
         <variableId>b49a55f8-eb25-440f-af08-55d06dae3c81</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>45c9ffe0-d617-4ec2-959b-8f63daba41a1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Authentication/SIMON - Log Out</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>04732f19-6a0f-42b2-b6fa-1da46d6ded82</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Authentication/SIMON - Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>985760d5-185a-4d76-b142-7f94078923ea</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Approver Bisnis SME NPP</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>985760d5-185a-4d76-b142-7f94078923ea</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>645b335f-eed9-48af-9a2f-cde5e6941ca2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>76fcb69f-65ae-45fc-90f2-ca20a3b65ac0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Approver Progress/SIMON - Approver</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>83e10d5e-1fb1-4b40-9095-35ff94c9929c</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/SME Hijau CIF</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>83e10d5e-1fb1-4b40-9095-35ff94c9929c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>cif</value>
         <variableId>df754ae2-d67c-4498-b067-d692e2bfd901</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>51481bdb-4416-4d3c-a696-4aec6f77add7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Authentication/SIMON - Log Out</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>5577ac70-f1fc-40e0-b627-19c4ab99e5c2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Authentication/SIMON - Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>0f375e30-a78e-439c-845d-2fc6126ab140</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Approver Risiko SME NPP</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>0f375e30-a78e-439c-845d-2fc6126ab140</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>645b335f-eed9-48af-9a2f-cde5e6941ca2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>75e9604b-fb98-4b44-a310-a6ebb08b163e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Approver Progress/SIMON - Approver</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>a5e92000-c17a-4b81-ac4a-178d370fe7f6</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/SME Hijau CIF</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>a5e92000-c17a-4b81-ac4a-178d370fe7f6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>cif</value>
         <variableId>df754ae2-d67c-4498-b067-d692e2bfd901</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f500bb1f-a828-45cb-8548-6d6cf1c6a068</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Authentication/SIMON - Log Out</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
