<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Keterangan_1</name>
   <tag></tag>
   <elementGuidId>3f036c38-d34e-468a-85f4-835ac6ee9eed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[(@name = 'Keterangan') and (@id = 'Keterangan') and @class and contains(concat(' ', normalize-space(@class), ' '), ' form-control ') and contains(concat(' ', normalize-space(@class), ' '), ' custom-mrgnbttm ') and (@autocomplete = 'off')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;Keterangan&quot;]#Keterangan.form-control.custom-mrgnbttm[autocomplete=&quot;off&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#FormDataJawaban #Keterangan</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>4dd47a0f-a279-4aee-965c-afa28e412e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fa3c6550-dbe7-4e95-b999-f2220d1933ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control custom-mrgnbttm</value>
      <webElementGuid>dd8b552d-603c-46fc-8072-4098eb8cf068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Keterangan</value>
      <webElementGuid>62a3c84b-4944-4b2c-ad04-5a082bbcf941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Keterangan</value>
      <webElementGuid>0bc75a55-5ee4-45a8-81a5-df0c17ee1e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>a54ca38b-b0a9-4f86-9e7f-061da8484503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>9da4fcdb-00c0-4be1-ba8f-51c6a30d92e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0eda9cac96c5c137204c4179bfcaf248</value>
      <webElementGuid>50591d73-ff9e-4cc8-8e77-fe1599234160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//textarea[(@name = 'Keterangan') and (@id = 'Keterangan') and @class and contains(concat(' ', normalize-space(@class), ' '), ' form-control ') and contains(concat(' ', normalize-space(@class), ' '), ' custom-mrgnbttm ') and (@autocomplete = 'off')]</value>
      <webElementGuid>986d26ed-2ac6-4e28-9565-b9ce796ee41e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[(@name = 'Keterangan') and (@id = 'Keterangan') and @class and contains(concat(' ', normalize-space(@class), ' '), ' form-control ') and contains(concat(' ', normalize-space(@class), ' '), ' custom-mrgnbttm ') and (@autocomplete = 'off')]</value>
      <webElementGuid>9c0cd404-9706-4b99-b180-52761dfd6602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Keterangan' and @name = 'Keterangan']</value>
      <webElementGuid>5c63a1af-6a71-49cf-b87d-a429536d1714</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
