<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kode</name>
   <tag></tag>
   <elementGuidId>3ebc6c78-2940-4186-882a-2385b547764a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'Kode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Kode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#Kode</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>57b20f57-e80a-411a-bdfb-15db9bf010e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0563301d-d780-4e73-a23d-75498f3d69f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>b8eee382-e926-4c98-9111-3a4a7b51f640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Kode</value>
      <webElementGuid>2ea5879c-06e5-456a-a518-292230dd8d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Kode</value>
      <webElementGuid>a07b1b97-a972-4b0b-b875-a0d95e904ea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^[\sa-zA-Z0-9\?!@#$%^&amp;*\-=_+{}\[\]|,.:()~`]*$</value>
      <webElementGuid>d9499a0a-2a8d-4c9a-b3ea-c7fa293a5e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>Bad Request</value>
      <webElementGuid>603ed9b0-1b0f-42b3-9549-43b32226ee25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b835c6a2-eb6e-4225-88ce-a2e6eecf2622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>51b83eae-d0f8-4bb6-89bb-907dbe07c150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bc4bea75-f462-452d-aa82-a921c7751cb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-303b17b630698f9ee03cf4aade4d50c9</value>
      <webElementGuid>46c18c49-c244-4ad4-b312-2bcbcb056b65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'Kode']</value>
      <webElementGuid>52a54834-0294-437a-bb10-f74d5cb44517</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'Kode']</value>
      <webElementGuid>5d1b889d-5621-48bc-b2f4-428a54291835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'Kode' and @id = 'Kode']</value>
      <webElementGuid>6b9da4f7-3eef-49f5-ab31-cb24c3fa1313</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
