<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_txtNamaSearchParam</name>
   <tag></tag>
   <elementGuidId>01cfce01-be51-496d-ad88-3400988ac120</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'txtNamaSearchParam']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtNamaSearchParam</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtNamaSearchParam</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>20520117-6da6-40ab-af9e-e1f93fe80c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>87f7e9b2-97f2-40ac-8cf7-9c1d4111339b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7ca8553e-8872-42b6-9448-6c775e3b133d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtNamaSearchParam</value>
      <webElementGuid>f76acadd-0a97-44e6-9735-7cc4a60c879e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-111763c618ea82a11dcc008c9cf1b214</value>
      <webElementGuid>1694e7c8-018e-498d-b4fa-31f2d89eb8ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'txtNamaSearchParam']</value>
      <webElementGuid>1f39caa9-2b47-4778-b192-c6fc26e5209b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'txtNamaSearchParam']</value>
      <webElementGuid>ab84b56a-c810-4d08-bf82-59c17de176d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtNamaSearchParam']</value>
      <webElementGuid>d10c9ca1-6820-470d-91bf-fc973e8c6744</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
