<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kode_1</name>
   <tag></tag>
   <elementGuidId>6defc198-c7a7-402a-885e-54bf29edaed9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'FormDataJawaban']//*[@id = 'Kode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FormDataJawaban #Kode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#FormDataJawaban #Kode</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e204202a-28ce-4586-bbe1-79c6310ff881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4bc38377-716e-461b-8801-d5ac11b845fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>fc6bb4d5-4b54-40fa-8b96-4b9a0873a709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Kode</value>
      <webElementGuid>e98be480-bd67-4a91-a121-d4bdc622fc6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Kode</value>
      <webElementGuid>8e7e001b-5829-49cf-ad5c-e087dc84f8c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>ac90c94d-2836-419d-86d6-31c7c375c658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b9c07575-22e1-42b4-be34-2e988479a117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-8ff64f417abf863bc50f8ceecb7d9bfb</value>
      <webElementGuid>6618b60a-8a46-4d9d-ac0a-226d42c3b722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'FormDataJawaban']//*[@id = 'Kode']</value>
      <webElementGuid>3f31d515-1697-4b05-abbc-119b2c368c87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'FormDataJawaban']//*[@id = 'Kode']</value>
      <webElementGuid>f4e91a50-fdf7-4dd3-8a2f-3aff03f667e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Kode' and @name = 'Kode' and @type = 'text']</value>
      <webElementGuid>ae2cbb10-00fd-4c5f-85e8-4dc8716fb651</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
