<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Isactive</name>
   <tag></tag>
   <elementGuidId>cb105edd-fc67-4150-ae06-cdd01a594676</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[(@id = 'Isactive') and (@value = 'False')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Isactive[value=&quot;False&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#Isactive >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>34000990-3558-4fcb-82d0-7eced0880947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>False</value>
      <webElementGuid>f10187b1-cda4-44ee-9a43-030eeb9acd13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>65507261-7155-42ed-8e64-a32302b1fa4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>c05f734f-0cef-4f36-97bc-34c8b716f9ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Isactive</value>
      <webElementGuid>f58bf8b7-8297-4c5e-aa24-98fd880b7903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Isactive</value>
      <webElementGuid>cbc71bce-c83e-4951-b518-3c3f6469c510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-1b06a31cdd9e9d642f4bc16e3a05c1e4</value>
      <webElementGuid>82279995-872d-4f8e-9f02-89c3e32b0e35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@id = 'Isactive') and (@value = 'False')]</value>
      <webElementGuid>18c1feb0-368c-40ab-8a06-d2318f4191f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@id = 'Isactive') and (@value = 'False')]</value>
      <webElementGuid>d940b6b9-c4ca-4ece-8fa6-8acc73386e88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'Isactive' and @id = 'Isactive']</value>
      <webElementGuid>c6fc7d88-fa4e-456c-8d71-46d9f1c2db65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
