<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PembuatanMts</name>
   <tag></tag>
   <elementGuidId>dca724cf-63f0-425c-be98-3fa016bb2628</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[(@name = 'PembuatanMts') and (@id = 'PembuatanMts') and (@value = 'False')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;PembuatanMts&quot;]#PembuatanMts[value=&quot;False&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#PembuatanMts >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5988a27c-26e8-4946-b490-806eaab0e98d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>False</value>
      <webElementGuid>36216cb7-592a-4993-8273-edfe44b8fc46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>5bed1aae-9726-42f6-aff7-0024858ee92d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>9460ecd6-ffb1-43fd-9102-56896ae36cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PembuatanMts</value>
      <webElementGuid>ce88a220-96ea-44dc-bf9b-3f24cf49c02b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PembuatanMts</value>
      <webElementGuid>98504785-62d5-4513-8c78-ce528692d6d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-f0458b07b87166d2d67dd419db26dd64</value>
      <webElementGuid>d22ad44a-662b-48ee-96e8-fedfa8bfb10a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@name = 'PembuatanMts') and (@id = 'PembuatanMts') and (@value = 'False')]</value>
      <webElementGuid>b5553091-bcda-4e8a-9655-d8ac991d232e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@name = 'PembuatanMts') and (@id = 'PembuatanMts') and (@value = 'False')]</value>
      <webElementGuid>f86ad999-7ee4-400c-98a1-1c122e10a631</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'PembuatanMts' and @id = 'PembuatanMts']</value>
      <webElementGuid>ec011dca-8c7d-4ea9-bd5c-909ebf2b961a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
