<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CreateLookup</name>
   <tag></tag>
   <elementGuidId>ff3194af-099d-4b81-9d61-650713193b18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'CreateLookup']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CreateLookup</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Tambah Data&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>77542f70-8f21-42a1-8f96-96a0f275b0f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info mb-2</value>
      <webElementGuid>a4394b6a-5e30-4943-b301-afa3dcd877a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CreateLookup</value>
      <webElementGuid>7d61ea37-470e-4403-8103-64c272d951b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah Data</value>
      <webElementGuid>60d22e6f-64cc-4c13-b652-9afc73eb4e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-20b8f2d72dd0e49f8bceb4c638015419</value>
      <webElementGuid>4f3d0e7b-f46e-4fed-9683-4f5c3bbda7ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'CreateLookup']</value>
      <webElementGuid>f3ec7920-c66a-474e-9d25-367a87144fac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'CreateLookup']</value>
      <webElementGuid>b5485c8f-17df-4903-9888-1ba43162cec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'CreateLookup' and (text() = 'Tambah Data' or . = 'Tambah Data')]</value>
      <webElementGuid>fc8088fd-bb9e-4e6b-a374-8c72ecd59b45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
