<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_IsActive</name>
   <tag></tag>
   <elementGuidId>c5476c7f-ea42-46c1-92de-1f169d3f6eea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@value = 'False']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[value=&quot;False&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#IsActive >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>965c042d-52c1-443a-beff-4a71a127291d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IsActive</value>
      <webElementGuid>5876893b-e57c-4212-a2e7-5ece9772bef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IsActive</value>
      <webElementGuid>4a3fbb70-98be-48ef-87cf-bde2acb63443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>fd058cb7-83c9-4ea5-bd97-b7439c336276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>fae11a67-e138-4f6e-9d2b-1ebcde48a295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>False</value>
      <webElementGuid>9f0df6a2-66de-42be-9661-980a925fb2c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-025f74dbbcb019da68f9a17c650d75f6</value>
      <webElementGuid>1db5760a-bfd0-4a0a-81cc-c89346871a03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@value = 'False']</value>
      <webElementGuid>8a9b95b4-18cd-4da4-b91d-d323abe4eb86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@value = 'False']</value>
      <webElementGuid>2cff5f07-fc79-4a40-a6c0-7e606b8776ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'IsActive' and @name = 'IsActive' and @type = 'radio']</value>
      <webElementGuid>8534a90c-0789-4d96-9b81-70c6ac1ed808</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
