<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_IsActive</name>
   <tag></tag>
   <elementGuidId>11dea190-236d-42ed-a184-d5f1c55d79b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@value = 'False']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[value=&quot;False&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#IsActive >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0cf7b302-ef91-47b7-987c-6355bd3d931f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>False</value>
      <webElementGuid>67a2bf8e-2ea5-4ca9-9fa2-31780377b629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>b5abfb45-8156-48c4-83e2-c3b87de5717b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>c326fcf2-d68f-4a87-b745-16fe847afa19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IsActive</value>
      <webElementGuid>6d986ec5-1318-43eb-b870-5208d5942ea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IsActive</value>
      <webElementGuid>bb716437-4fba-4056-8833-6a34b56f9a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-025f74dbbcb019da68f9a17c650d75f6</value>
      <webElementGuid>01a007e7-fb47-43fd-8d14-41bc1a9cbfef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@value = 'False']</value>
      <webElementGuid>8a68a20c-a511-43c3-9cce-1e545971b432</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@value = 'False']</value>
      <webElementGuid>683afe03-d584-46f1-bb79-04a7978fc47f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'IsActive' and @id = 'IsActive']</value>
      <webElementGuid>70a7607c-ebad-4ef1-94d3-b88557d7f0b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
