<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_button-delete</name>
   <tag></tag>
   <elementGuidId>38b04f9f-b1fe-4d73-b627-9e2905d81454</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-delete</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'button-delete']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Delete&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0fb8d75c-3a9d-4a09-b3b4-0df17cc61c0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>b26edd4c-0c88-43ab-9db3-50aaf3de11e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>4a30f7fb-acf3-4761-b0df-de1fbdd5ba28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-delete</value>
      <webElementGuid>5c8fe4bb-37f9-422a-a4c8-a20474d474e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>138792</value>
      <webElementGuid>60283aef-27c8-4443-99ec-4dbbbbf9fd25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cif</name>
      <type>Main</type>
      <value>43718202556</value>
      <webElementGuid>4bf2a30f-a153-4c8d-8991-e06a0143ce9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nama</name>
      <type>Main</type>
      <value>TEST KUALITATIF UPLOAD FILE</value>
      <webElementGuid>7e2f53b3-5a5c-45c7-8fd6-24c9cb92d1ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>4fc08250-9f0e-4ffc-bc18-67573a61ad20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-ac879564428cb66c7feee706e950afb0</value>
      <webElementGuid>bae33683-4094-42e5-8646-c2e948184c07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'button-delete']</value>
      <webElementGuid>6724b6e6-65fe-45cb-909b-802fa2cfaf07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'button-delete']</value>
      <webElementGuid>2511fe16-bc38-469a-bc8c-b040dce4f2b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'button-delete' and (text() = 'Delete' or . = 'Delete')]</value>
      <webElementGuid>a897bafb-8ba3-4803-b6cb-a95579ec0fbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
