<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_43718202556</name>
   <tag></tag>
   <elementGuidId>89f6a481-26eb-4a79-ac09-da4762b40eec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.odd:nth-child(1) td:nth-child(5)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' odd ') and (position() = 1)]//*[(name() = 'td') and (position() = 5)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=gridcell[name=&quot;43718202556&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>3da241cd-be82-4b64-8456-70cdc18ee0da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>43718202556</value>
      <webElementGuid>60661b2b-ff2e-4df7-8d0e-7241df50555d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-3ca3fa706cb9100483c8ebbaaa2e4427</value>
      <webElementGuid>c8cfc619-6a63-4231-9612-3e9e136d9a36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' odd ') and (position() = 1)]//*[(name() = 'td') and (position() = 5)]</value>
      <webElementGuid>88fe725f-335d-4532-b1c0-ead2aafa7349</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' odd ') and (position() = 1)]//*[(name() = 'td') and (position() = 5)]</value>
      <webElementGuid>6af651f7-a3f6-4cad-9b09-5a51c1fd7f91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '43718202556' or . = '43718202556')]</value>
      <webElementGuid>d2c23492-4732-48fc-979d-a0ee39d4292b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
