<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_BackBtn</name>
   <tag></tag>
   <elementGuidId>16e78a73-597c-46ed-9c24-acef364f310d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BackBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'BackBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Batal&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d7422991-5f5d-40d5-a4c3-2965f51566ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BackBtn</value>
      <webElementGuid>e88f3d2a-1670-4663-ba62-eae294c2a641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7e36f9f4-ada6-4020-8b46-e52e60d4b8dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger</value>
      <webElementGuid>2877f1e8-58fc-47cd-a39b-d5fdfc4bb948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Batal
                            </value>
      <webElementGuid>fc17122a-4b63-4c73-9de4-792cdfe311ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a479bd6bd9ff5a6ca416b17da16f5d7d</value>
      <webElementGuid>6a375c4b-1bb7-4ef9-ab01-af5a6b5715a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'BackBtn']</value>
      <webElementGuid>0c82d71c-8a04-4777-b5b3-d602e324baaa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'BackBtn']</value>
      <webElementGuid>26df3925-e3d3-4e81-910d-eed0b3849e96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'BackBtn' and @type = 'button' and (text() = '
                                Batal
                            ' or . = '
                                Batal
                            ')]</value>
      <webElementGuid>0617fef3-4657-4998-8eb3-50f3e3bc0574</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
