<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_button-edit</name>
   <tag></tag>
   <elementGuidId>6f69557c-bbe3-4da7-b1ec-6b74499016ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-edit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'button-edit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>57470520-c450-43ea-ac93-f860dbd6be97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-small btn-facebook</value>
      <webElementGuid>9e9f8fdf-d2e5-40fc-b373-fa6d6829790f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-edit</value>
      <webElementGuid>dea61e2d-50f5-42f5-a4ba-8be4bb674d6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>117</value>
      <webElementGuid>37a176f5-be08-4b15-bac9-422f91c089da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>d6590e02-6b28-44b7-9b7a-e84dfc2e8cc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ubah Data</value>
      <webElementGuid>381720c5-1ab1-4920-9a84-99100d3068e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-49cea1513c9c05926579ff07ad9958c9</value>
      <webElementGuid>785771df-5d67-4682-ac0f-da0351a3ddb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'button-edit']</value>
      <webElementGuid>2d64f706-bf6e-4202-8ea9-eded7b3e14d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'button-edit']</value>
      <webElementGuid>cbfa7a9a-6a37-4cee-9ed7-210de06b0084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'button-edit' and @title = 'Ubah Data']</value>
      <webElementGuid>468a37b6-8701-4e90-baab-cb16738608ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
