<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_button-delete</name>
   <tag></tag>
   <elementGuidId>3e86a56a-9ede-4d3c-9da7-0ea2489d6a9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-delete</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'button-delete']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a2dd1d57-6ab7-4299-b316-1b5f76e873e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-small btn-facebook</value>
      <webElementGuid>d0b93158-5951-4358-986d-75739864ba14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-delete</value>
      <webElementGuid>0e6a84ab-7f01-4d59-91c4-f31c9ff9c030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>117</value>
      <webElementGuid>e21552a3-ae9d-4233-bc4d-88068d543d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>06f4ff84-c1d1-4f88-a8de-c8cf998b7934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Delete Data</value>
      <webElementGuid>fa699d42-1821-45c4-96a1-a55863fd4a80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-ac879564428cb66c7feee706e950afb0</value>
      <webElementGuid>f69d320e-7d53-4546-8e1a-a83565c078e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'button-delete']</value>
      <webElementGuid>a53b1491-5022-4da8-b4d4-0dd3a7b78c8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'button-delete']</value>
      <webElementGuid>e8ed658f-6f2d-406c-98ca-16a5c554a052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'button-delete' and @title = 'Delete Data']</value>
      <webElementGuid>458c5936-85ee-4c73-b94b-fad1934520d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
