<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_button-view</name>
   <tag></tag>
   <elementGuidId>830b2b1c-8c6f-49da-a691-070c8d3fb039</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-view</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'button-view']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3f48b666-debe-4c9c-98a0-8832c46ca52c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-small btn-facebook</value>
      <webElementGuid>f04c3c54-a2c0-4e73-b0a6-d33846af0257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-view</value>
      <webElementGuid>fcf95298-1c7a-4d06-b2f2-c38f7e2ed740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>117</value>
      <webElementGuid>96d4be0a-31b8-4137-a7af-2af4c008f266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>32bbeed1-aede-4453-a042-db4d91cdb1f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>View Data</value>
      <webElementGuid>cf1fe1b5-dc8e-4a7d-a6ca-4c88fee321e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-356200560c1dd6a8332c225636912ee6</value>
      <webElementGuid>2e5aa0e2-c8f9-4790-b9b3-128e8a6b6ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'button-view']</value>
      <webElementGuid>6d8cca55-b5e6-4a44-9013-d6d22e9b7a61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'button-view']</value>
      <webElementGuid>489611c8-21fc-4e83-8a46-f0392005dd21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'button-view' and @title = 'View Data']</value>
      <webElementGuid>67085ce7-29de-48fa-936e-68a3bb6008e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
