<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_txtNamaSearchParam</name>
   <tag></tag>
   <elementGuidId>7ee0e829-a385-47d4-8ac0-92c6098bc04d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtNamaSearchParam</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'txtNamaSearchParam']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtNamaSearchParam</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a584fb1-201e-418b-a99d-4158164c5fc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6f41aa0d-baca-4318-9829-243a2cf0f69d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c4d1cc92-36fc-4f1c-b451-3246b55e7f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtNamaSearchParam</value>
      <webElementGuid>86474ab8-e9f1-4a0a-afdc-6f9f68d408d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-111763c618ea82a11dcc008c9cf1b214</value>
      <webElementGuid>1a31c462-5c72-4316-a9a3-6755f1f9e09d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'txtNamaSearchParam']</value>
      <webElementGuid>d42c12f1-69cd-45c0-a48d-655020afbe8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'txtNamaSearchParam']</value>
      <webElementGuid>c4ea1b89-4c36-48ee-b0b2-23fa8fd2f0bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtNamaSearchParam']</value>
      <webElementGuid>c859ea62-7806-4cfa-8e09-70d1a4f3c089</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
