<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Nama</name>
   <tag></tag>
   <elementGuidId>57ee8f02-1751-4b16-a4c9-7bfad83c3bc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Nama</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'Nama']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#Nama</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>4beda853-143e-4518-93c0-7b015509f997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>16892a0f-e8aa-4ac3-834d-e61c47d263b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>4bea6b52-0762-4f0d-b298-fe24bd2e3080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Nama</value>
      <webElementGuid>cc3e6a29-c2a0-4e98-94d0-4997ffccfc6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Nama</value>
      <webElementGuid>71ba3618-4263-4d32-861e-737d780e8fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control custom-mrgnbttm</value>
      <webElementGuid>72038c99-b0f2-470c-9c51-c17a0e492d4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2768fd4d-9573-4909-9711-9d0acf0206fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-9fd934c27f10f86d5d53755913a528e9</value>
      <webElementGuid>bd5d6779-8170-42eb-88d1-76c8f9f43027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'Nama']</value>
      <webElementGuid>6958b297-0261-44a0-9cb0-e7cc1e6d684d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'Nama']</value>
      <webElementGuid>8f536342-e4b0-4c5a-be35-eac2f94ae851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'Nama' and @id = 'Nama']</value>
      <webElementGuid>ca121578-5c92-440d-a67d-f19ea41b74b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
