<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_btn-formkualitatif</name>
   <tag></tag>
   <elementGuidId>8a5ced16-abd9-4f75-b8a4-3f9cbf48db2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-formkualitatif</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'btn-formkualitatif']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Form SIMON Kualitatif&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7e531dfc-d9f5-4e29-a0b3-43d2ea638819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>675ebcb7-e843-41f8-9cd3-e32293331dee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>b8d57075-db50-4d6c-8cdb-5e1f81bd60bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-formkualitatif</value>
      <webElementGuid>6798e27c-b686-47ed-92a8-dfea1dbe0ed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>138803</value>
      <webElementGuid>4012d3ef-ae8d-4833-934e-2a1e04a7398c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-segmen</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>f2b0f76d-70b8-4b4a-9376-e10bcab42465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Form SIMON Kualitatif</value>
      <webElementGuid>361c8498-5d9b-4955-8d46-89e6bf746ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-37354bbaa94d8c0eceb1a7938111bc53</value>
      <webElementGuid>76b8ea88-3bb2-477c-a7ec-5c63976b0b5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'btn-formkualitatif']</value>
      <webElementGuid>3cc1340a-7c17-46db-a177-72db101357c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'btn-formkualitatif']</value>
      <webElementGuid>dd22d753-32bc-4185-9c98-cc10a0ac37bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'btn-formkualitatif' and (text() = 'Form SIMON Kualitatif' or . = 'Form SIMON Kualitatif')]</value>
      <webElementGuid>1e6ce55f-8980-48b5-99b8-6dbb4551321a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
