<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pilar-18</name>
   <tag></tag>
   <elementGuidId>a3024865-5121-4b1a-b086-306f84606402</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' nav-item ') and (@role = 'presentation') and (name() = 'li') and (position() = 3)]//*[@data-toggle = 'tab']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.nav-item[role=&quot;presentation&quot;]:nth-child(3) [data-toggle=&quot;tab&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Pilar-3
KEMAMPUAN MEMBAYAR&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>65a057e1-2e7a-4943-95e6-0b25d89192be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>67b57a18-f71e-4f45-94e4-71549d2dfb60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>Pilar-18</value>
      <webElementGuid>82a0dbbf-5d6d-4720-a57e-d51616efc702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>af85f607-b8b3-43ab-b3a6-a004f9a018a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#TabPilar-18</value>
      <webElementGuid>a6aea302-d6df-4bad-ad38-4fe188678c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>50db5a2c-be60-4fe3-adca-1049611d235c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Pilar-18</value>
      <webElementGuid>480b99bd-3381-4a3e-a67b-10a2850b9960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>046af843-cdd4-4e7a-bf20-20358f80a6a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilar-3
KEMAMPUAN MEMBAYAR</value>
      <webElementGuid>f96d8f1b-b151-4f2a-a22a-44b9bfd7e242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-5b7a20b0af5602ae5ccab95c593d3322</value>
      <webElementGuid>f615ca39-8e40-4957-89b4-8296f46e4448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' nav-item ') and (@role = 'presentation') and (name() = 'li') and (position() = 3)]//*[@data-toggle = 'tab']</value>
      <webElementGuid>46e162e6-cb35-48c8-ba2e-2f5ff3ca86c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' nav-item ') and (@role = 'presentation') and (name() = 'li') and (position() = 3)]//*[@data-toggle = 'tab']</value>
      <webElementGuid>143c9fe4-ff1b-4f19-94b2-82f3d8fbfa55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#TabPilar-18' and @id = 'Pilar-18' and (text() = 'Pilar-3
KEMAMPUAN MEMBAYAR' or . = 'Pilar-3
KEMAMPUAN MEMBAYAR')]</value>
      <webElementGuid>119af78f-307d-494a-9a58-48fab832503c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
