<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pilar-17</name>
   <tag></tag>
   <elementGuidId>bd287a86-696c-434c-ab9d-2ae1b51e9c6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'FormRincianPenilaian']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' nav-item ') and (@role = 'presentation') and (name() = 'li') and (position() = 2)]//*[@data-toggle = 'tab']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FormRincianPenilaian li.nav-item[role=&quot;presentation&quot;]:nth-child(2) [data-toggle=&quot;tab&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Pilar-2
KINERJA DEBITUR&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1bfc8e06-4f3e-4ec8-b9d0-a7d74b5f5d8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>76708081-21fb-41b4-bbd2-a969a5973c89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>Pilar-17</value>
      <webElementGuid>ac7a3f35-6b54-4472-b8eb-da20412b1a0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>fdfe1a0c-8460-4a21-9bc6-8f232083dbc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#TabPilar-17</value>
      <webElementGuid>189e214e-8688-4e94-bdb0-427ce49216cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>3ad869d8-49cb-47b6-a64d-b0981fe31857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Pilar-17</value>
      <webElementGuid>98fabe0d-a4d6-4b7e-9398-abf95a15059e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>2bd348e4-0588-41ed-ad2a-0b5178455b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilar-2
KINERJA DEBITUR</value>
      <webElementGuid>be726760-f5ba-47f6-9dc1-b7a4eeb0a717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-83a50fb2b20fbe9d00754b5b95ab6f44</value>
      <webElementGuid>a9da0676-1038-488f-a25f-66f1bee60abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'FormRincianPenilaian']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' nav-item ') and (@role = 'presentation') and (name() = 'li') and (position() = 2)]//*[@data-toggle = 'tab']</value>
      <webElementGuid>873f5f28-f1f5-42e1-92d3-f38b9547d1ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'FormRincianPenilaian']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' nav-item ') and (@role = 'presentation') and (name() = 'li') and (position() = 2)]//*[@data-toggle = 'tab']</value>
      <webElementGuid>f33116a2-cfa4-41d6-8da6-9266fc5b149e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#TabPilar-17' and @id = 'Pilar-17' and (text() = 'Pilar-2
KINERJA DEBITUR' or . = 'Pilar-2
KINERJA DEBITUR')]</value>
      <webElementGuid>22ad6d9b-20da-4120-ba86-27107f3113e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
