<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pilar-3</name>
   <tag></tag>
   <elementGuidId>91670be1-ea29-4f19-b525-0514f9fc2192</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.nav-item[role=&quot;presentation&quot;]:nth-child(3) [data-toggle=&quot;tab&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' nav-item ') and (@role = 'presentation') and (name() = 'li') and (position() = 3)]//*[@data-toggle = 'tab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Pilar-3 KEMAMPUAN MEMBAYAR&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>88e07e71-fd17-47d4-b7d3-1bf6cb4141f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e653f094-f011-4b7c-865f-07bcc8dff713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>Pilar-3</value>
      <webElementGuid>6a7db395-8be4-4de9-894e-d4de3858142e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>72500104-1270-4d61-bc33-d851277a55d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#TabPilar-3</value>
      <webElementGuid>033d3783-2b1c-4df9-b6f5-08d93db06c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>17bf0679-39c1-4a07-905f-ade8d423f4e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Pilar-3</value>
      <webElementGuid>2dae7984-5ec5-4a62-a0fa-3bc9ddf799ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>7d699b07-8836-4b28-b4c7-f96ebc06986a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilar-3 KEMAMPUAN MEMBAYAR</value>
      <webElementGuid>ac172bf9-8194-454a-a01e-7314f0ce9828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-5b7a20b0af5602ae5ccab95c593d3322</value>
      <webElementGuid>708dc42d-0a16-403c-b113-1f94eb01e0bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' nav-item ') and (@role = 'presentation') and (name() = 'li') and (position() = 3)]//*[@data-toggle = 'tab']</value>
      <webElementGuid>eda5e4f6-b1e0-49f5-8150-9f6da321dfb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' nav-item ') and (@role = 'presentation') and (name() = 'li') and (position() = 3)]//*[@data-toggle = 'tab']</value>
      <webElementGuid>2ba81e40-3e32-429a-8594-9d9648951f4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#TabPilar-3' and @id = 'Pilar-3' and (text() = 'Pilar-3 KEMAMPUAN MEMBAYAR' or . = 'Pilar-3 KEMAMPUAN MEMBAYAR')]</value>
      <webElementGuid>94e0d6e5-dc7f-40cb-b9a2-1db1b5b1344b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
