<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pilar-2</name>
   <tag></tag>
   <elementGuidId>4d31d2b4-e10b-43ea-92d6-3b703fd0b0d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#FormRincianPenilaian li.nav-item[role=&quot;presentation&quot;]:nth-child(2) [data-toggle=&quot;tab&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'FormRincianPenilaian']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' nav-item ') and (@role = 'presentation') and (name() = 'li') and (position() = 2)]//*[@data-toggle = 'tab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Pilar-2 KINERJA DEBITUR&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>996a4f16-29a4-4696-91f2-2caf4c56ef7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4d45075c-3a5f-464c-a758-a0da5d8dd947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>Pilar-2</value>
      <webElementGuid>66c47d6f-18ed-4d7d-9d0c-335d4f358085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>692444f3-1449-4cc4-8df2-1e0d2d42f1dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#TabPilar-2</value>
      <webElementGuid>00901289-3d26-4962-ab47-c28506b55148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>88a9f4eb-979c-4c12-8d85-5640f0d9ecc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Pilar-2</value>
      <webElementGuid>e7b8b57b-8f3d-431a-b0d3-5357dc7e7f21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>3d17b557-a096-4a62-b186-c98bfd06404a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilar-2 KINERJA DEBITUR</value>
      <webElementGuid>44e4b610-a74f-4324-b994-38b17d87a84f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-83a50fb2b20fbe9d00754b5b95ab6f44</value>
      <webElementGuid>75ca1d74-d496-4920-b54c-4f24ea867112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'FormRincianPenilaian']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' nav-item ') and (@role = 'presentation') and (name() = 'li') and (position() = 2)]//*[@data-toggle = 'tab']</value>
      <webElementGuid>c6efbed5-e119-467c-a862-b26695445dd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'FormRincianPenilaian']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' nav-item ') and (@role = 'presentation') and (name() = 'li') and (position() = 2)]//*[@data-toggle = 'tab']</value>
      <webElementGuid>f7989bca-ac34-406d-9331-2cf03fe61dc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#TabPilar-2' and @id = 'Pilar-2' and (text() = 'Pilar-2 KINERJA DEBITUR' or . = 'Pilar-2 KINERJA DEBITUR')]</value>
      <webElementGuid>85d4c6ac-a8b8-43f4-bbf6-8743fddcb75d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
