<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_TabInformasiDebitur</name>
   <tag></tag>
   <elementGuidId>22bc60ca-be98-471f-ae5f-94b6bd0084fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'TabInformasiDebitur']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#TabInformasiDebitur</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '#TabInformasiDebitur-Page' and @id = 'TabInformasiDebitur' and (text() = 'Informasi Debitur' or . = 'Informasi Debitur')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Informasi Debitur&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0d105f56-d26b-4295-b424-f60c1b845351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>002e70d0-db97-442e-bd7b-9cfca6c441d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>Memorandum</value>
      <webElementGuid>9d76814c-6283-469a-9cca-2df84b27616f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>3b6e1533-e8a8-4c0f-8987-0bff08923376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#TabInformasiDebitur-Page</value>
      <webElementGuid>8d836f9a-9437-445c-b9e3-09a8c46a7310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>aab39ecf-c435-4ef7-ad31-320daa6b2d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TabInformasiDebitur</value>
      <webElementGuid>6d342de3-80ea-4d9a-9b6b-13325eb87c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>e534c805-ee38-4409-97a6-3d546c32cafe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Informasi Debitur</value>
      <webElementGuid>04e7fc7a-6d7d-40f5-98d4-3c73671fe02c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-af28a601cf5bd2fa7d8d6beaf15ff568</value>
      <webElementGuid>fab90196-053f-4d7b-a3e6-239dc9cf7e2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'TabInformasiDebitur']</value>
      <webElementGuid>a69febee-9235-4bcc-8086-114185ea182c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'TabInformasiDebitur']</value>
      <webElementGuid>80258360-3194-4d26-abe3-a1b1c805816f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#TabInformasiDebitur-Page' and @id = 'TabInformasiDebitur' and (text() = 'Informasi Debitur' or . = 'Informasi Debitur')]</value>
      <webElementGuid>e3dad687-7e75-4ef3-b7df-40905e9579c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
