<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_TabInformasiDebitur</name>
   <tag></tag>
   <elementGuidId>22bc60ca-be98-471f-ae5f-94b6bd0084fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TabInformasiDebitur</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'TabInformasiDebitur']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Informasi Debitur&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0ead0936-90a8-4dfa-a57e-14c928100e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8d734f4c-74d2-4a64-b03f-d72c3d88180c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>Memorandum</value>
      <webElementGuid>a781418b-b30e-4fd5-9861-e57964623e3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>87cb173d-2e22-4d9c-999e-347223b084fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#TabInformasiDebitur-Page</value>
      <webElementGuid>fb2b0d67-127c-4113-84bf-760e60d3260a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>66d1b34f-97fd-4818-ae2f-9d30ed77d991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TabInformasiDebitur</value>
      <webElementGuid>e296c2ae-b14c-4c34-9e01-39f66e9c55f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>b57bf8cc-71fb-4c54-98b5-12accfd6dbb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Informasi Debitur</value>
      <webElementGuid>cf892f0e-a587-4b2b-8028-47342fbf284e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-af28a601cf5bd2fa7d8d6beaf15ff568</value>
      <webElementGuid>ca70dfef-0969-4c81-a758-3d03059adc25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'TabInformasiDebitur']</value>
      <webElementGuid>af5b57bc-b34c-4001-8aa2-e922fbabc524</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'TabInformasiDebitur']</value>
      <webElementGuid>6d14c138-2919-4902-ba26-a8604fc67b4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#TabInformasiDebitur-Page' and @id = 'TabInformasiDebitur' and (text() = 'Informasi Debitur' or . = 'Informasi Debitur')]</value>
      <webElementGuid>5e9b0090-6e83-4f25-9c51-2a382ec313f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
