<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CreateUploadBtn</name>
   <tag></tag>
   <elementGuidId>07e540a3-538e-49e6-9341-1973cf3d8e31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CreateUploadBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'CreateUploadBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Tambah Data&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>668493ad-52f0-4b23-8a59-363c761bc492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CreateUploadBtn</value>
      <webElementGuid>4dd4a3fc-fecb-4ac7-9fbc-581aa269e9b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info mb-2 custom-clrwht</value>
      <webElementGuid>53d87630-fd95-41d4-b3d6-91a4882955fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah Data</value>
      <webElementGuid>389f2c8d-22e7-434c-ae39-bfc2fdded420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e1ce2dcf1dbf0bafa3929ab2b6ee6313</value>
      <webElementGuid>0d8343d9-4110-4498-999c-a9272e305eae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'CreateUploadBtn']</value>
      <webElementGuid>83877c9b-cec9-420c-90d4-61588793e205</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'CreateUploadBtn']</value>
      <webElementGuid>ac54d77c-a70d-4cc3-b44a-d0da306ec3fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'CreateUploadBtn' and (text() = 'Tambah Data' or . = 'Tambah Data')]</value>
      <webElementGuid>8aef68c8-e94d-413a-bb55-a410ca243fc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
