<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Action</name>
   <tag></tag>
   <elementGuidId>5c6fe886-97f4-4642-82b7-81f9642d2ff1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TableBelumDiniali .btn-info</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'TableBelumDiniali']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-info ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Action&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9d0986ef-b841-40cd-907c-6799cc9eea25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>55c39e5e-d12f-4788-9cc8-093d1ee8f4e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info dropdown-toggle</value>
      <webElementGuid>6a09c524-23c6-4305-9d41-9c0c8fa151e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>18bf84f4-3a6f-4f00-8bd2-9eb641c5c0b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1b7788eb-81bb-4d66-93e8-ce74ac588c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b918e803-ecbf-42f3-9e43-fbd50cc9cbd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Action</value>
      <webElementGuid>63b26b60-290b-4dd4-9fb7-61cdd271e939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e63587a09c14660685b31f4dfb92314f</value>
      <webElementGuid>ea844266-170e-46d1-9e6d-3cc5f9017564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'TableBelumDiniali']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-info ')]</value>
      <webElementGuid>603ec8ca-d082-434a-bb3d-84220b9bda7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'TableBelumDiniali']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-info ')]</value>
      <webElementGuid>04f4cb7e-32b7-453b-a069-992f497af87e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Action' or . = 'Action')]</value>
      <webElementGuid>91b101ac-c4c0-4a2d-8490-18b4e3555089</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
