<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Action</name>
   <tag></tag>
   <elementGuidId>5c6fe886-97f4-4642-82b7-81f9642d2ff1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.odd[role=&quot;row&quot;]:nth-child(1) .btn-info</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' odd ') and (@role = 'row') and (position() = 1)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-info ')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and (text() = 'Action' or . = 'Action')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>td >> internal:has-text=&quot;ActionForm SIMON Kualitatif&quot;i >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3a38d4aa-2683-4713-87aa-62179874821e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c30594f2-d1fd-4892-afbf-141dd2130ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info dropdown-toggle</value>
      <webElementGuid>4cc54907-6e92-4144-a72b-ba7c4ed713be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>ea3a58f1-0984-4aac-8979-0a9cb840fa31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2965fe47-7816-4f62-94e3-c891b2dae3cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>663dc296-12f8-424c-b5a2-47a444befc92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Action</value>
      <webElementGuid>c36b877f-5ba3-44c8-876c-591f74d6f936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0dd00049d174ccf49c43e78d55851590</value>
      <webElementGuid>1cccb731-950d-4dbe-a574-80315b296468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' odd ') and (@role = 'row') and (position() = 1)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-info ')]</value>
      <webElementGuid>48fe37ab-3921-4114-8148-fa7312892d24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' odd ') and (@role = 'row') and (position() = 1)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-info ')]</value>
      <webElementGuid>d1e54fef-81e2-4901-973c-b014480eddf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Action' or . = 'Action')]</value>
      <webElementGuid>73465aac-92f3-4b5b-996d-c99b06edc9ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'TableBelumDiniali']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-info ')]</value>
      <webElementGuid>04f4cb7e-32b7-453b-a069-992f497af87e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
