<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_nav-profile-img mr-2</name>
   <tag></tag>
   <elementGuidId>f51c7343-67f0-45eb-b2b2-7a3b9c9ca191</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.nav-profile-img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' nav-profile-img ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6e2c78cb-b5a9-4ec0-982d-03f45aa80cec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-profile-img mr-2</value>
      <webElementGuid>96717683-e66f-4c53-870a-b914d551df9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/lib/breeze/images/faces/face1.jpg</value>
      <webElementGuid>47a6d626-db9b-4f95-9e1a-71e06dd8bc58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-fdcbff016c3d454902534ea3828cb850</value>
      <webElementGuid>5c8000e2-026d-4cb0-9a4b-fe61c5f87363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' nav-profile-img ')]</value>
      <webElementGuid>d413c58e-eb21-45d0-9ec2-99c0fe1ba658</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' nav-profile-img ')]</value>
      <webElementGuid>add33385-f20d-4a21-bd89-b038d88e8b2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/lib/breeze/images/faces/face1.jpg']</value>
      <webElementGuid>3166965e-ca74-4f75-9fbf-798620875f94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
