<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MaksimumKreditString</name>
   <tag></tag>
   <elementGuidId>69b12ceb-4102-4e02-baf4-bdbb82757bf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MaksimumKreditString</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'MaksimumKreditString']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#MaksimumKreditString</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>78ed3f13-7071-4f03-9a00-f532cc3f2d96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4ac99e12-7bf1-4122-a976-e80c238befe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>ec93c3ca-fa82-4401-9627-6d1a75e69bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MaksimumKreditString</value>
      <webElementGuid>3ac9814e-cb7c-40dc-8234-706681ac7f13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MaksimumKreditString</value>
      <webElementGuid>a593a59f-f32a-4462-a15f-fb58a97e9c45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>16342285-7f2a-444c-8acd-ec3bc0b8dd80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>26ecb972-db72-4d66-8e08-a50a9907d81a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-c314a4302a5bd4e4a93e29686c418eb4</value>
      <webElementGuid>b7e30c58-a68b-4083-a0bc-fe1b3fb5e2fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'MaksimumKreditString']</value>
      <webElementGuid>1626ec8e-f77a-47d5-98fa-b66fd4168606</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'MaksimumKreditString']</value>
      <webElementGuid>9b4c28b9-1215-48e3-a592-b75612f1afef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'MaksimumKreditString' and @id = 'MaksimumKreditString']</value>
      <webElementGuid>ba811ea0-6648-403d-9cfc-f0472652bc60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
