<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_35572 - ANDREAN PALONGGAM - Corporate Banking_1</name>
   <tag></tag>
   <elementGuidId>e5ca8c0e-3c2e-4781-a9ca-85e748765f9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[role=&quot;option&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@role = 'option']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;35572 - ANDREAN PALONGGAM - Corporate Banking 3&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>725783b3-f490-4726-accb-9f20ac2c9c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>7cd96ac0-0bcc-48a2-831f-21684ed7b160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>531e871d-e6eb-4e92-b11b-b0cbc073c844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>babc4474-da1e-44db-ab93-67e21b05e66c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>248</value>
      <webElementGuid>04b1ec89-a8ed-4d9b-83e5-5167a5eb3507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>35572 - ANDREAN PALONGGAM - Corporate Banking 3</value>
      <webElementGuid>df4bca88-2476-4d0b-83a0-4381dcc5cb16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-aa05a2136210d9be8768266b332a2787</value>
      <webElementGuid>2dc97f4a-4cb5-4505-8187-f14d4289d3f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@role = 'option']</value>
      <webElementGuid>693decc8-d631-4c33-8bc5-36d713e1972b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@role = 'option']</value>
      <webElementGuid>8e6bfa4e-d248-4545-934c-bd5b95e05d9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '35572 - ANDREAN PALONGGAM - Corporate Banking 3' or . = '35572 - ANDREAN PALONGGAM - Corporate Banking 3')]</value>
      <webElementGuid>d950335a-a682-4620-b3ec-aea3f78baea6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
