<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Call (Kontak Debitur) terkait monitor  verif</name>
   <tag></tag>
   <elementGuidId>049a6280-25c2-454a-9405-5564ca951ea9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[(@role = 'option') and (position() = 3)]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[role=&quot;option&quot;]:nth-child(3)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Call (Kontak Debitur) terkait monitor &amp; verifikasi usaha debitur dan dilampirkan melalui upload dokumen dengan format PDF' or . = 'Call (Kontak Debitur) terkait monitor &amp; verifikasi usaha debitur dan dilampirkan melalui upload dokumen dengan format PDF')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Call (Kontak Debitur) terkait monitor &amp; verifikasi usaha debitur dan dilampirkan melalui upload dokumen dengan format PDF&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>4d316c88-a38d-424f-8ea6-9f3ae1b8f6f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>0f1af06f-e242-4549-b701-d49bcf4294b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>4253901f-5aca-4434-9edc-242ef79e9fb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>50dbbad9-8305-42e4-a1e3-33261217dcbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>93</value>
      <webElementGuid>da746108-c400-4c0d-b693-d1ade859d314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Call (Kontak Debitur) terkait monitor &amp; verifikasi usaha debitur dan dilampirkan melalui upload dokumen dengan format PDF</value>
      <webElementGuid>17ff6671-421c-45a7-9cfd-8749d6f36914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d8e3ca259a282ee70258f821bc844051</value>
      <webElementGuid>e28eb512-7312-4a42-bf0b-7f6032e99c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@role = 'option') and (position() = 3)]</value>
      <webElementGuid>c51d66c3-1dac-4960-863e-c72ccebd3d6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@role = 'option') and (position() = 3)]</value>
      <webElementGuid>f75cefe3-74b2-436d-bc87-f56b2ca98eda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Call (Kontak Debitur) terkait monitor &amp; verifikasi usaha debitur dan dilampirkan melalui upload dokumen dengan format PDF' or . = 'Call (Kontak Debitur) terkait monitor &amp; verifikasi usaha debitur dan dilampirkan melalui upload dokumen dengan format PDF')]</value>
      <webElementGuid>2fea73dc-2092-441f-abb9-9a3ea1d6ff6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
