<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Melakukan kunjungan setempat_site visit dan d</name>
   <tag></tag>
   <elementGuidId>a5ec388b-7d66-44ae-97a9-c489a39852fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[role=&quot;option&quot;]:nth-child(5)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[(@role = 'option') and (position() = 5)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Melakukan kunjungan setempat/site visit dan dilampirkan melalui upload dokumen dengan format PDF&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>5ed2fd00-618f-46eb-9503-58cbe67dc4db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>21479b59-135c-45c2-9687-6c5446881093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>f5af9d08-38ae-4369-922d-1955fa822808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>76f871d1-8e09-4cda-8a89-e14da17164ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>119</value>
      <webElementGuid>fe8e9443-451e-4dd6-a805-6bc945c1ef26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Melakukan kunjungan setempat/site visit dan dilampirkan melalui upload dokumen dengan format PDF</value>
      <webElementGuid>43b59688-ce16-4b4d-b63a-1e2fa50bde35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-964c1ced603b3788b0ceb54f09848614</value>
      <webElementGuid>88bc3f41-3290-4045-b60c-6e68c4ffcabc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@role = 'option') and (position() = 5)]</value>
      <webElementGuid>bfcd2cff-700c-4a84-a9d5-d1eb4b672489</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@role = 'option') and (position() = 5)]</value>
      <webElementGuid>efbcef75-28d5-4856-8b96-3f7748342fea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Melakukan kunjungan setempat/site visit dan dilampirkan melalui upload dokumen dengan format PDF' or . = 'Melakukan kunjungan setempat/site visit dan dilampirkan melalui upload dokumen dengan format PDF')]</value>
      <webElementGuid>5f2c6b4d-18e4-4b04-a2a9-d55cfae3fced</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
