<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Monitoring penyaluran mutasi keuangan, efekti</name>
   <tag></tag>
   <elementGuidId>3da6754c-62bc-42e9-8d33-e6e764874b85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[(@role = 'option') and (position() = 2)]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[role=&quot;option&quot;]:nth-child(2)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Monitoring penyaluran mutasi keuangan, efektivitas/kewajaran penggunaan kredit dan dilampirkan melalui upload dokumen dengan format PDF' or . = 'Monitoring penyaluran mutasi keuangan, efektivitas/kewajaran penggunaan kredit dan dilampirkan melalui upload dokumen dengan format PDF')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Monitoring penyaluran mutasi keuangan, efektivitas/kewajaran penggunaan kredit dan dilampirkan melalui upload dokumen dengan format PDF&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>5d21c3c4-3f6c-4019-a877-735bee0da63d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>585560a6-c3ed-403d-a41e-7eb5f3f835cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>af776655-da58-4e30-bc3c-caec94d08398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>44eaea67-b85d-4d64-9e2e-1a03ef84b15d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>069afd5c-8771-49cd-8c4f-a74828da8708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Monitoring penyaluran mutasi keuangan, efektivitas/kewajaran penggunaan kredit dan dilampirkan melalui upload dokumen dengan format PDF</value>
      <webElementGuid>f9067894-297f-4acd-b62f-8beb16f0cd26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-7cea6358c17f3fcafe32e993a1ac5a3f</value>
      <webElementGuid>5bbb658d-6ee1-48cc-a06c-6d8ab4eeb44e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@role = 'option') and (position() = 2)]</value>
      <webElementGuid>db4b0969-9b97-47a5-93e8-bf948ebb0188</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@role = 'option') and (position() = 2)]</value>
      <webElementGuid>be768b5e-bb93-41e0-a39a-193c21b1d511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Monitoring penyaluran mutasi keuangan, efektivitas/kewajaran penggunaan kredit dan dilampirkan melalui upload dokumen dengan format PDF' or . = 'Monitoring penyaluran mutasi keuangan, efektivitas/kewajaran penggunaan kredit dan dilampirkan melalui upload dokumen dengan format PDF')]</value>
      <webElementGuid>a1d60a4a-e58d-4a77-8a8d-15549f15b6e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
