<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Monitoring jaminan bergerak dan tidak bergera</name>
   <tag></tag>
   <elementGuidId>77d28b3c-de11-4dc1-854c-388748943a94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[(@role = 'option') and (position() = 4)]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[role=&quot;option&quot;]:nth-child(4)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Monitoring jaminan bergerak dan tidak bergerak, termasuk verifikasi penilaian jaminan, dan pemantauan kesempurnaan pengikatan jaminan. Dilampirkan melalui upload dokumen dengan format PDF' or . = 'Monitoring jaminan bergerak dan tidak bergerak, termasuk verifikasi penilaian jaminan, dan pemantauan kesempurnaan pengikatan jaminan. Dilampirkan melalui upload dokumen dengan format PDF')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Monitoring jaminan bergerak dan tidak bergerak, termasuk verifikasi penilaian jaminan, dan pemantauan kesempurnaan pengikatan jaminan. Dilampirkan melalui upload dokumen dengan format PDF&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>7f9188d3-29a9-4033-94b0-9f9ed1f96907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>0742d0bb-94d7-447e-9fdc-43071cff4876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>5d543534-9495-4ef5-983a-7c0388814f39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>05f55509-5e44-460e-bc4d-6a477cb12b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>106</value>
      <webElementGuid>e307d5e2-0c88-4545-b64f-220c0da14937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Monitoring jaminan bergerak dan tidak bergerak, termasuk verifikasi penilaian jaminan, dan pemantauan kesempurnaan pengikatan jaminan. Dilampirkan melalui upload dokumen dengan format PDF</value>
      <webElementGuid>59d91f7a-5e0f-487d-863e-fa63d7d5968f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a2fc4237b447912142f8e47f1e5d0571</value>
      <webElementGuid>3bc1eb2a-0fb6-4f5a-924b-e31fd3a757e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@role = 'option') and (position() = 4)]</value>
      <webElementGuid>4b6bebff-a954-4fe5-a61e-cd8ad103cbfe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@role = 'option') and (position() = 4)]</value>
      <webElementGuid>702b372f-cbe9-4836-8f87-7193e8a0677b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Monitoring jaminan bergerak dan tidak bergerak, termasuk verifikasi penilaian jaminan, dan pemantauan kesempurnaan pengikatan jaminan. Dilampirkan melalui upload dokumen dengan format PDF' or . = 'Monitoring jaminan bergerak dan tidak bergerak, termasuk verifikasi penilaian jaminan, dan pemantauan kesempurnaan pengikatan jaminan. Dilampirkan melalui upload dokumen dengan format PDF')]</value>
      <webElementGuid>13def76c-47cf-4938-8c09-43691499359a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
