<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Melakukan kunjungan setempat_site visit dan d</name>
   <tag></tag>
   <elementGuidId>a5ec388b-7d66-44ae-97a9-c489a39852fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[(@role = 'option') and (position() = 5)]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[role=&quot;option&quot;]:nth-child(5)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Melakukan kunjungan setempat/site visit dan dilampirkan melalui upload dokumen dengan format PDF' or . = 'Melakukan kunjungan setempat/site visit dan dilampirkan melalui upload dokumen dengan format PDF')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Melakukan kunjungan setempat/site visit dan dilampirkan melalui upload dokumen dengan format PDF&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>5546c489-6642-47e7-8e1b-412ac7569bb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>e893484e-2fb9-48ba-967c-b5dca45222eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>c6314d19-00e3-4f67-ac90-678c86d2bc73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4d4b2849-3eaf-4c88-8fc1-60fa77aa883f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>119</value>
      <webElementGuid>6ea82ccb-1b1a-446d-bb70-d8784ed30872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Melakukan kunjungan setempat/site visit dan dilampirkan melalui upload dokumen dengan format PDF</value>
      <webElementGuid>212b9638-48b9-4376-a683-9ee97446cde2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-964c1ced603b3788b0ceb54f09848614</value>
      <webElementGuid>6e8c737f-f399-45a2-b324-959f59ad75f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@role = 'option') and (position() = 5)]</value>
      <webElementGuid>c741c79d-9898-4e5f-9dab-6fd3e4e42c35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@role = 'option') and (position() = 5)]</value>
      <webElementGuid>1a0c71a3-3441-4d99-b38d-f98fe0bb0643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Melakukan kunjungan setempat/site visit dan dilampirkan melalui upload dokumen dengan format PDF' or . = 'Melakukan kunjungan setempat/site visit dan dilampirkan melalui upload dokumen dengan format PDF')]</value>
      <webElementGuid>e7b9fcd9-7a2a-4f01-a9a8-bd511213b8b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
