<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_select2-IdAktivitas-container_1</name>
   <tag></tag>
   <elementGuidId>31962801-305f-4199-b8b1-bbdf2def3868</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[aria-labelledby=&quot;select2-IdAktivitas-container&quot;] [aria-readonly=&quot;true&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-labelledby = 'select2-IdAktivitas-container']//*[@aria-readonly = 'true']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#select2-IdAktivitas-container</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>55650822-05eb-40ba-8dd3-8aff752344a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>692a0949-8374-4935-bc29-0074cd4e0f79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-IdAktivitas-container</value>
      <webElementGuid>7fd065a3-e128-407e-814e-f8ce96745d7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>57c8af5d-5816-4f68-9fcf-2da4836294e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c4ad2ec1-2f34-4286-b0cc-96587d71c22e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-Silahkan pilih-</value>
      <webElementGuid>12e3aede-47cd-4331-b52a-461477c05c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-710770cb9f2bca2be3edaab3db706696</value>
      <webElementGuid>2baac7f0-263a-4086-92c0-7d159131d7b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-labelledby = 'select2-IdAktivitas-container']//*[@aria-readonly = 'true']</value>
      <webElementGuid>f8d039b3-0163-4d3f-ab3e-2a17eed3ccd0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-labelledby = 'select2-IdAktivitas-container']//*[@aria-readonly = 'true']</value>
      <webElementGuid>36249b80-f332-4e58-98ca-2623218ccafe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-IdAktivitas-container' and (text() = '-Silahkan pilih-' or . = '-Silahkan pilih-')]</value>
      <webElementGuid>140aa295-5df6-42f4-bae4-a88cdac98a23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
