<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_select2-Approver1-container_1</name>
   <tag></tag>
   <elementGuidId>ad2a194e-b469-42ab-84ce-cfaae5dfac45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[aria-labelledby=&quot;select2-Approver1-container&quot;] [aria-readonly=&quot;true&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-labelledby = 'select2-Approver1-container']//*[@aria-readonly = 'true']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#select2-Approver1-container</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4cd2a026-8c5b-429b-8f44-f9194607a0e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>507ab39d-559d-464e-a267-1f916e3dd425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-Approver1-container</value>
      <webElementGuid>ca931100-f3c9-4c3d-ad20-69b9d162c434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>b40be655-5325-404d-9d85-086d24fc2f75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8e0e5ee3-01d1-4cbe-9462-deebc73a5236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-Silahkan pilih-</value>
      <webElementGuid>e65b03d3-8379-42f3-b8da-30aaa4fc2f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-19ea7130ebc0034f23864e79244b3979</value>
      <webElementGuid>ad156745-3c7e-4606-b00d-31c4c67d0ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-labelledby = 'select2-Approver1-container']//*[@aria-readonly = 'true']</value>
      <webElementGuid>7ca36a7b-e7d7-4bfa-8779-f7230bbb73ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-labelledby = 'select2-Approver1-container']//*[@aria-readonly = 'true']</value>
      <webElementGuid>ad92c5fb-702e-4e5b-ba15-02fa7d026f4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-Approver1-container' and (text() = '-Silahkan pilih-' or . = '-Silahkan pilih-')]</value>
      <webElementGuid>cbe1681b-9f68-405b-9eb5-a44a678a56c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
