<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_BidangUsaha</name>
   <tag></tag>
   <elementGuidId>aeaaf4b3-bbfc-4023-8551-f84ad68af76b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'BidangUsaha']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BidangUsaha</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'BidangUsaha' and @id = 'BidangUsaha']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#BidangUsaha</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>582110b1-edde-4e23-b1d7-a49dd0fa04cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>c0a914aa-9606-4c11-90d6-8b4de27c7a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BidangUsaha</value>
      <webElementGuid>59a2b456-391c-4b5f-a584-de6834d9856f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BidangUsaha</value>
      <webElementGuid>8dad8383-9f83-4a2e-9212-29f4c41eb9f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control custom-hght75px</value>
      <webElementGuid>d6b85123-cc1b-44e3-a062-de84ef515277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>abbbc2bb-f491-40fb-a1a9-290b37e9101b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-049c6a920a0b32861cab86f796bbfa85</value>
      <webElementGuid>34574a01-f51d-450a-8ce5-34438223d944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'BidangUsaha']</value>
      <webElementGuid>3e3b423a-10fc-48be-881c-33818894188b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'BidangUsaha']</value>
      <webElementGuid>8be175f8-2359-49e7-8c30-589059544f64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'BidangUsaha' and @id = 'BidangUsaha']</value>
      <webElementGuid>6f0794f0-5b49-4b6e-859b-b5de8cfc4b1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
