<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_PemenuhanDsra</name>
   <tag></tag>
   <elementGuidId>97b5a760-d800-4e86-a41f-6bb601809ef1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PemenuhanDsra</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'PemenuhanDsra']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#PemenuhanDsra</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>bd5cdc51-40b8-4f72-aada-badcf508cd08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>fdb402a8-613d-4f0e-bd94-fb2b141e8b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PemenuhanDsra</value>
      <webElementGuid>46a54698-6b8f-4894-a2a0-0d76b602244e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PemenuhanDsra</value>
      <webElementGuid>d3984476-548c-4cec-a104-2e95e63b1d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control custom-hght75px</value>
      <webElementGuid>16ad5cb1-0612-457f-8706-2916df5bfb32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7f2230fa-6ee7-4a9a-ab90-a90de6c6a88a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-15b46041dbcf3e653a72848339c27590</value>
      <webElementGuid>6cd39db2-3936-429e-a809-372ed92041cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'PemenuhanDsra']</value>
      <webElementGuid>5adde1c2-4c45-4710-961e-c6b67e8b27e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'PemenuhanDsra']</value>
      <webElementGuid>dad892aa-32e2-4484-bd42-df046d85c9b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'PemenuhanDsra' and @id = 'PemenuhanDsra']</value>
      <webElementGuid>6031c2a5-57cd-41b6-a3fc-8a2969537200</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
