<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Type your text here</name>
   <tag></tag>
   <elementGuidId>392a9253-2df7-4355-9469-8659dd1e608d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'komentar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#komentar</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'komentar' and @placeholder = 'Type your text here']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Type your text here&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>ac33d730-4b58-4dec-b0cd-2d29fb413825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>komentar</value>
      <webElementGuid>42e09102-e683-404d-bf92-92fa9a788147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9b7b5bd9-3589-49b9-a9ed-8154558c83c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>ea897a54-018d-4da9-9645-3faf02b56f7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type your text here</value>
      <webElementGuid>31abac85-5466-4096-9143-6501d3fbc6ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-8c3a05648b85baa9ede3b0b7754c9481</value>
      <webElementGuid>e12758ef-58f9-4d64-be1b-ba9612ec1d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'komentar']</value>
      <webElementGuid>57ce1603-30df-45ad-9284-7fa121a92e8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'komentar']</value>
      <webElementGuid>8747f288-b654-43e0-9138-63bac2138266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'komentar' and @placeholder = 'Type your text here']</value>
      <webElementGuid>8d2cbade-5ede-420e-9e8b-2216a555d664</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
