<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Type your text here</name>
   <tag></tag>
   <elementGuidId>392a9253-2df7-4355-9469-8659dd1e608d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#komentar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'komentar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Type your text here&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>e4a3986e-f1ff-4ec5-8868-3e307afafd19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>komentar</value>
      <webElementGuid>008b5fcf-912c-434a-9984-e2e5ec4e07b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d2b73e49-d7b4-47d9-b31f-ea4c9f2e4dd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>44bbdb19-1331-45b3-be0e-47549fb908b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type your text here</value>
      <webElementGuid>df61b515-6d93-4223-a83a-014688211a1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-8c3a05648b85baa9ede3b0b7754c9481</value>
      <webElementGuid>df0b33ab-665d-4903-9e04-77cadcec0a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'komentar']</value>
      <webElementGuid>1ee23116-d087-463c-87c9-2b5cc75d9989</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'komentar']</value>
      <webElementGuid>f606b9f9-4a3e-4c89-b2d2-e08464ab9b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'komentar' and @placeholder = 'Type your text here']</value>
      <webElementGuid>77aa802c-6b84-4aa9-901a-1582207a7268</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
