<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_BidangUsaha</name>
   <tag></tag>
   <elementGuidId>aeaaf4b3-bbfc-4023-8551-f84ad68af76b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BidangUsaha</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'BidangUsaha']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#BidangUsaha</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d6b09108-e169-40dc-89ac-6be78d105e19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>71829f25-aa8a-4664-8a16-2d81e8367239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BidangUsaha</value>
      <webElementGuid>5c68e857-dbd0-4b3d-b8c9-0fb0c63f7907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BidangUsaha</value>
      <webElementGuid>d0653bb4-0d15-428c-8866-b6495bad1086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control custom-hght75px</value>
      <webElementGuid>b957fdf9-e0ac-4882-9602-7fa23d74e226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fd166563-f2f5-4153-bc13-44d7a20c148b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-049c6a920a0b32861cab86f796bbfa85</value>
      <webElementGuid>23d9698d-4792-4b4e-af51-2fca8ba0b790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'BidangUsaha']</value>
      <webElementGuid>ee8e3042-80c0-4539-942e-ca54c22564c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'BidangUsaha']</value>
      <webElementGuid>9abb2ac0-2184-4cd6-8282-1c97e26b8809</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'BidangUsaha' and @id = 'BidangUsaha']</value>
      <webElementGuid>d4bef589-0181-4334-ad67-882d677214a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
