<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_PemenuhanDsra</name>
   <tag></tag>
   <elementGuidId>97b5a760-d800-4e86-a41f-6bb601809ef1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'PemenuhanDsra']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PemenuhanDsra</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'PemenuhanDsra' and @id = 'PemenuhanDsra']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#PemenuhanDsra</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>9748db4e-aff1-4e09-ae5d-dd6c2a539398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>17d9b029-9aeb-47b6-aa26-8742cc75176e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PemenuhanDsra</value>
      <webElementGuid>229229c8-109a-4360-861b-7861e162fa4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PemenuhanDsra</value>
      <webElementGuid>9e61d53f-daa9-416b-94c6-7a28063f080d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control custom-hght75px</value>
      <webElementGuid>24721d43-5646-4378-b37f-de75e455f29a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c61dbd45-a79b-4b56-a4f8-ed3bb6202110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-15b46041dbcf3e653a72848339c27590</value>
      <webElementGuid>bbe635a1-4643-483a-a906-485c1db2c55e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'PemenuhanDsra']</value>
      <webElementGuid>568901e2-236a-4cf1-ad3a-c7daa428e2c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'PemenuhanDsra']</value>
      <webElementGuid>c2248b7c-c979-431c-b4f7-f65190733cc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'PemenuhanDsra' and @id = 'PemenuhanDsra']</value>
      <webElementGuid>a6d118be-c846-49c6-9a0a-8b92b5b06cdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
