<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Keterangan</name>
   <tag></tag>
   <elementGuidId>fa68c364-b215-428f-b026-a5bce9bdb0ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'Keterangan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Keterangan</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'Keterangan' and @name = 'Keterangan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#Keterangan</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>91177e5d-47ea-4c21-9322-0ef7520643bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js-example-placeholder-multiple js-states form-control custom-wdthrndm</value>
      <webElementGuid>a6343ef1-dcd9-4b0d-85a1-89ae09d21786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Keterangan</value>
      <webElementGuid>44d9bec6-d064-4782-840c-aed53a699de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Keterangan</value>
      <webElementGuid>d9aa09fd-d202-4385-9395-68a4ea98f46a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-227ada21a5fb78597846abf2ecc2570a</value>
      <webElementGuid>203d9522-7979-47a7-adbf-497910e1ce79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'Keterangan']</value>
      <webElementGuid>31427232-6c8c-4623-9d0c-c92288ab5b9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'Keterangan']</value>
      <webElementGuid>09e981bc-994a-4862-81fa-c39a1ffe3ab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Keterangan' and @name = 'Keterangan']</value>
      <webElementGuid>11aef232-462d-414f-a394-cda19c6f79c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
