<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_IndikasiMasalah</name>
   <tag></tag>
   <elementGuidId>1042f7e7-fd83-41b0-8347-90b3a3c10938</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#IndikasiMasalah</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'IndikasiMasalah']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#IndikasiMasalah</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>3f4f702d-d05d-429d-882d-d1e190169e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>0452f161-7838-47cb-9c1f-8c797778d407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IndikasiMasalah</value>
      <webElementGuid>55997dec-f870-4143-83b0-6f71c06a80a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IndikasiMasalah</value>
      <webElementGuid>a63921ac-0ba2-4a9b-bd70-5542fc5f3505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control custom-hght75px</value>
      <webElementGuid>8d4f7eeb-3b9a-43b8-81cf-ce68f66bf672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>276e2b6f-ec41-40a4-8961-12da80063aa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e3c57c0f5c18ee91ddbf378f91c260c3</value>
      <webElementGuid>29eb6f0e-98ec-46c8-9326-144dd32112c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'IndikasiMasalah']</value>
      <webElementGuid>04fa0157-8c87-45e5-b5f1-0bbe6f54bb92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'IndikasiMasalah']</value>
      <webElementGuid>d7c87fdb-3acf-44e1-b09f-80a3c35d5c84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'IndikasiMasalah' and @id = 'IndikasiMasalah']</value>
      <webElementGuid>b2444f02-97dd-4049-be93-4493656fe823</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
