<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_IndikasiMasalah</name>
   <tag></tag>
   <elementGuidId>1042f7e7-fd83-41b0-8347-90b3a3c10938</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'IndikasiMasalah']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#IndikasiMasalah</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'IndikasiMasalah' and @id = 'IndikasiMasalah']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#IndikasiMasalah</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>9fcac3fb-bd8a-4f8c-92b4-c83a51b25943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>dd8d064a-18c2-47df-8cec-ef59513e6841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IndikasiMasalah</value>
      <webElementGuid>2bbc0047-f212-45ba-8b76-d11564eef344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IndikasiMasalah</value>
      <webElementGuid>23fefafd-5593-4c11-b31c-cd83de246730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control custom-hght75px</value>
      <webElementGuid>19605378-c7ff-496d-a87c-6e059ed2f944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6e3a37f5-0260-45d1-89e8-6140bbece6ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e3c57c0f5c18ee91ddbf378f91c260c3</value>
      <webElementGuid>6c147c03-ea86-44c1-a1dc-ea7630f7f022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'IndikasiMasalah']</value>
      <webElementGuid>27509ffd-20f8-4313-956a-1796d2106808</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'IndikasiMasalah']</value>
      <webElementGuid>676364af-4440-47bd-bfa8-8f11f8da9193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'IndikasiMasalah' and @id = 'IndikasiMasalah']</value>
      <webElementGuid>aa4b7394-12ea-49ce-98da-319d9c96ae34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
