<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_IsActive</name>
   <tag></tag>
   <elementGuidId>0900bf67-f3ac-4a3f-b77b-1c9d371eec35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@value = 'False']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[value=&quot;False&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#IsActive >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b8bb806b-6103-4c14-aa47-8a60223c9898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>False</value>
      <webElementGuid>00bbe627-ec0d-41e3-9826-944f93cd838f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>873700ed-75d5-4dd6-bcaf-f33f35b1dd32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>37b52cc4-e2de-4244-a485-9e5f9a4dde6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IsActive</value>
      <webElementGuid>63b99fb9-a372-4ec0-9108-eae5d41f4974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IsActive</value>
      <webElementGuid>f8c57d08-c002-438f-a3e2-ae9684540511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-025f74dbbcb019da68f9a17c650d75f6</value>
      <webElementGuid>5cb82fb0-32c5-462b-b78d-a0b1fc72216b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@value = 'False']</value>
      <webElementGuid>17df4646-1f83-4b34-b150-fb3df78ae0cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@value = 'False']</value>
      <webElementGuid>d4dd8678-ec1c-49d0-ba31-8ac65a74e2f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'IsActive' and @id = 'IsActive']</value>
      <webElementGuid>667cf09c-d652-4c19-9c10-f8eebf39f7a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
