<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_NamaFasilitas</name>
   <tag></tag>
   <elementGuidId>a7927fcc-0cda-4484-8ffd-9c4240f68395</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'NamaFasilitas']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NamaFasilitas</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'NamaFasilitas' and @id = 'NamaFasilitas']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#NamaFasilitas</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c2debf5c-df7d-4f10-8243-2885dcf85d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>c0f763ef-8bf9-4c0e-bda9-9fd636c4eab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>a82356a5-c260-431c-91c7-68c8ed1589dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NamaFasilitas</value>
      <webElementGuid>fec8dc10-716c-4611-a628-4bc5240fa182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NamaFasilitas</value>
      <webElementGuid>82ca9465-205b-4cd6-a8fe-bd25d7916b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control custom-mrgnbttm</value>
      <webElementGuid>c83c3f5f-fbcd-4925-9d79-8cbdbf778c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7eb9e0b8-ac72-467d-adac-93d18ffe6452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-da660765ead6c868d4c1c42ef037a0b3</value>
      <webElementGuid>329cde18-e5a2-41ab-a20a-fba9ff0d23d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'NamaFasilitas']</value>
      <webElementGuid>bd012470-8529-4978-8db0-3c668b945bab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'NamaFasilitas']</value>
      <webElementGuid>3bd49d3e-b064-4351-b043-bb5f031e3b70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'NamaFasilitas' and @id = 'NamaFasilitas']</value>
      <webElementGuid>fa92a535-035c-401e-baf2-45f4a03532d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
