<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_select2-Segmen-container</name>
   <tag></tag>
   <elementGuidId>54dfce5b-763e-431e-9e76-d965ef928c9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-labelledby = 'select2-Segmen-container']//*[@title = '-Silahkan pilih-']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[aria-labelledby=&quot;select2-Segmen-container&quot;] [title=&quot;-Silahkan\ pilih-&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#select2-Segmen-container</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4c5f1f21-2cb0-4ddb-8471-bd6e37c5f3fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>c4c82c89-c70f-4d6e-aee8-995af96b741c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-Segmen-container</value>
      <webElementGuid>cccd9255-8a10-4cf6-8886-6d4cd42e9352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>842924d6-de94-439b-a419-0aaaebef82cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2d22f144-1dd7-4128-9f87-11d0a7ab8bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>-Silahkan pilih-</value>
      <webElementGuid>5dc8b267-8f18-4f4b-be6f-72a8cb6e5fbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-Silahkan pilih-</value>
      <webElementGuid>4d618065-1427-489c-b583-7ef8b135e424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-bf18d3b12656cc17d92966313a2384df</value>
      <webElementGuid>1594590c-1930-4b53-ad76-cc19e924125d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-labelledby = 'select2-Segmen-container']//*[@title = '-Silahkan pilih-']</value>
      <webElementGuid>844b4b16-1f49-400c-9031-ed5e5dcbc128</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-labelledby = 'select2-Segmen-container']//*[@title = '-Silahkan pilih-']</value>
      <webElementGuid>885786fd-134e-4be7-b45b-9a69a01a4dfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-Segmen-container' and @title = '-Silahkan pilih-' and (text() = '-Silahkan pilih-' or . = '-Silahkan pilih-')]</value>
      <webElementGuid>4c313bcb-4b8c-4011-a998-eb15b6938b17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
