<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_No_ activate to sort column descending</name>
   <tag></tag>
   <elementGuidId>16ed48a4-0437-4959-be32-28f0477ce6df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[aria-label=&quot;No\:\ activate\ to\ sort\ column\ descending&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-label = 'No: activate to sort column descending']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;No: activate to sort column descending&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>89b86d4f-c9e1-4e45-b1cf-c05a3f4b5ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-wdth10px sorting_asc</value>
      <webElementGuid>9065742c-857f-419c-a998-0e93f0041782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>78384dc2-3049-435a-8583-74eaeab046fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>Table</value>
      <webElementGuid>f866dd79-8d16-4499-ac96-6a1ccbf65a35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rowspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>afacd00d-3718-4b99-99d1-24f11c8e2a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>bd623514-e81a-4ef7-93ed-60c1261982a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>No: activate to sort column descending</value>
      <webElementGuid>3dddb349-710e-401c-b819-4a634be060ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-sort</name>
      <type>Main</type>
      <value>ascending</value>
      <webElementGuid>18382092-5bf7-42bb-a60d-7351afd82a8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>06d83101-7de3-4cbc-adc6-e6f6b2bc8825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e49875c365139ecc73a3e6640745a8d3</value>
      <webElementGuid>1c4a138a-88ef-4d20-8adc-3f82f1074d5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-label = 'No: activate to sort column descending']</value>
      <webElementGuid>91a48c45-49ba-477e-bdbd-13a44139d4cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-label = 'No: activate to sort column descending']</value>
      <webElementGuid>95ab05a3-59f7-4ea5-94be-5ab9a6470a41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'No' or . = 'No')]</value>
      <webElementGuid>b1a15ccf-0ca6-4bd6-81b2-d10b59fbcf76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
