<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_btn_batal_view</name>
   <tag></tag>
   <elementGuidId>210b58a8-8d9a-4fe4-84d0-1c4c1a5a97b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_batal_view</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'btn_batal_view']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Batal&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1ecebac9-2842-4508-94b8-6ded99ae2a67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_batal_view</value>
      <webElementGuid>5f0b6825-e461-4a6d-8e12-1723d42d2385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c9965422-a6ad-45fa-acf8-06e92daca7ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger</value>
      <webElementGuid>b0358e24-9ad2-48a6-8476-57a3f1f4e21e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Batal
                            </value>
      <webElementGuid>24b02f37-01ee-4621-8ca0-748df3c66b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-65b29e752362fa37abffd312d8f2da07</value>
      <webElementGuid>508a0063-acba-4701-974e-557b531f8eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'btn_batal_view']</value>
      <webElementGuid>e5a27c4c-16ab-4dd5-a6cb-973762b144c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'btn_batal_view']</value>
      <webElementGuid>348b6fbf-3f85-4da5-9be6-b078e5663389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn_batal_view' and @type = 'button' and (text() = '
                                Batal
                            ' or . = '
                                Batal
                            ')]</value>
      <webElementGuid>b0e23d44-b17a-40ef-84d1-b0d0dfe2b163</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
