<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_btn_create_kewenangan</name>
   <tag></tag>
   <elementGuidId>ae56fe7c-053b-405a-b0da-0c142be193e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_create_kewenangan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'btn_create_kewenangan']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'btn_create_kewenangan' and (text() = 'Tambah Kewenangan' or . = 'Tambah Kewenangan')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Tambah Kewenangan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f4e8c467-3f0f-4f4b-9e09-2656df9b47a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_create_kewenangan</value>
      <webElementGuid>273b8de4-d5b4-455f-87b1-bb02ca0c9441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>6004</value>
      <webElementGuid>4f20b401-3275-4c1d-9c0a-d1db50ee2446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info mb-2 custom-clrwht</value>
      <webElementGuid>5d379e3a-3b45-4a15-bd75-890e73786ab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah Kewenangan</value>
      <webElementGuid>e5f4bc65-d9fd-40f9-adb7-1bb98fc69083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-253b56ad855dadd82c9bc7b3771b6d28</value>
      <webElementGuid>f28a8524-7f44-4b6f-a526-c113ad6cef9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'btn_create_kewenangan']</value>
      <webElementGuid>a81c89f7-295c-4c6a-87fd-9027a0642510</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'btn_create_kewenangan']</value>
      <webElementGuid>f60de1aa-46d4-4686-93d2-097142c7fdae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn_create_kewenangan' and (text() = 'Tambah Kewenangan' or . = 'Tambah Kewenangan')]</value>
      <webElementGuid>94083982-93fa-4e32-8d37-e4e44ea7c3f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
