<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_IsNonDefinitive_1</name>
   <tag></tag>
   <elementGuidId>8761e8c3-c654-4156-8337-b84d16f7a745</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-val-required=&quot;The\ IsNonDefinitive\ field\ is\ required\.&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-val-required = 'The IsNonDefinitive field is required.']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#IsNonDefinitive >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>45ab1aeb-0f4b-4533-8f22-573b48fd3b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>False</value>
      <webElementGuid>77b8b6cd-3407-49e4-bfda-b1796fcbad67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>d807a9d3-3080-46fd-ac71-eda3a65121f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>8cb44f99-e53e-4195-b685-3c6d85746572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IsNonDefinitive</value>
      <webElementGuid>b9a15a59-0acf-4082-a363-b591896b7c59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IsNonDefinitive</value>
      <webElementGuid>9b2d15f5-4213-465d-93fd-e5e4c6d26175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The IsNonDefinitive field is required.</value>
      <webElementGuid>6611bd67-83db-42d2-9e2e-bb7a325a42f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1c11ad5d-4276-4f32-ae51-de98b942cd84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-f60c237affd9168dcc977e81c1bcf6e2</value>
      <webElementGuid>8fcbd538-ff78-4c2b-a664-aa308258a88a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-val-required = 'The IsNonDefinitive field is required.']</value>
      <webElementGuid>25a7ad5d-ad80-49b6-8a80-f7f9bb56f46b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-val-required = 'The IsNonDefinitive field is required.']</value>
      <webElementGuid>9164f1bc-3e54-4cdb-a51b-eda275a81c71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'IsNonDefinitive' and @id = 'IsNonDefinitive']</value>
      <webElementGuid>6cb90e85-45ee-48e2-8897-fdd4881e48be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
