<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_IsActive</name>
   <tag></tag>
   <elementGuidId>6e779a29-f829-499f-a961-a0b3719cd8d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;IsActive&quot;]#IsActive[value=&quot;False&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[(@name = 'IsActive') and (@id = 'IsActive') and (@value = 'False')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#IsActive >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c6467a0b-d3b5-4306-aa26-e9a1376cde1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>False</value>
      <webElementGuid>2f503eb4-a225-4978-aa46-7f7600e3db0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>9db63024-0a94-4730-927b-45598a8e24af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>aaed692f-41f0-445c-b59f-e5b243b3aa41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IsActive</value>
      <webElementGuid>1cd7bebc-5dcd-4886-ab34-c01b3c7d002c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IsActive</value>
      <webElementGuid>c8336814-087b-4f0c-87c6-d882367318a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-559b4f21a5f2a6e8852e88dc3190066b</value>
      <webElementGuid>99881e03-6c4c-45e9-b656-40e05979d959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@name = 'IsActive') and (@id = 'IsActive') and (@value = 'False')]</value>
      <webElementGuid>35048e3c-b5a5-48be-9d50-fb6a1c6ba1f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@name = 'IsActive') and (@id = 'IsActive') and (@value = 'False')]</value>
      <webElementGuid>e7fd7ed7-12c9-4c52-8d30-8df0c2319445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'IsActive' and @id = 'IsActive']</value>
      <webElementGuid>bc23504c-cceb-40aa-b517-a7225848583c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
