<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_txtUnitSearchParam</name>
   <tag></tag>
   <elementGuidId>c4907199-5869-49f7-9876-dc3ce6ab546b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtUnitSearchParam</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'txtUnitSearchParam']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @id = 'txtUnitSearchParam']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtUnitSearchParam</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>825ac4ca-6112-4634-87a0-99cf0ce7cd59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e5d4a535-e036-4af2-b6ab-af9c4aaddd00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1c2f8a44-3a9d-412d-869f-deb117271e00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtUnitSearchParam</value>
      <webElementGuid>214a2495-27be-4afa-b782-676eddbb0772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-f348d384599f70bc04849d4e12202126</value>
      <webElementGuid>664efb71-fccc-4ef4-a926-8409cd8bebb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'txtUnitSearchParam']</value>
      <webElementGuid>51f3aee5-100e-4bb1-8d81-e6d7299dbf92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'txtUnitSearchParam']</value>
      <webElementGuid>c1f15cc2-7ad3-4b41-938b-f36e2f172e65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtUnitSearchParam']</value>
      <webElementGuid>59b170db-2e52-40da-a095-37538ed84449</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
