<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_txtNamaSearchParam</name>
   <tag></tag>
   <elementGuidId>e7b12204-0958-47c0-8f38-1cc66e3c335e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtNamaSearchParam</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'txtNamaSearchParam']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @id = 'txtNamaSearchParam']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtNamaSearchParam</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>58fae20b-ecc7-42ad-b239-17cc367f2a48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>18b8e9fd-1dd2-40a7-a08c-db2b64e6e42f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9ead1338-84e0-4aaa-8203-5a4242faf01e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtNamaSearchParam</value>
      <webElementGuid>b4e81adb-0d17-47d5-89cf-caa642ea61e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-111763c618ea82a11dcc008c9cf1b214</value>
      <webElementGuid>037e4f71-aae3-41ad-9a43-da6417a18f1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'txtNamaSearchParam']</value>
      <webElementGuid>f0bb1280-8940-43c0-9d89-7f437c8500ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'txtNamaSearchParam']</value>
      <webElementGuid>725d6f91-0b28-4c9d-b205-31b46435e1ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtNamaSearchParam']</value>
      <webElementGuid>af45aea5-9c19-4a56-bbd6-0278733afb06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
