<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_txtDateEnd</name>
   <tag></tag>
   <elementGuidId>80623e3c-ce85-4732-ab17-30628158e834</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtDateEnd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'txtDateEnd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtDateEnd</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cc70adac-6df7-4c17-a6a8-8c76c90d5956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtDateEnd</value>
      <webElementGuid>e4c88d91-c765-44d6-9cd8-69b393a39d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control custom-bckgrndclrwht hasDatepicker</value>
      <webElementGuid>07bf0750-af9a-489b-a93a-23927c6c41e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b2b0dafc-6dcb-4521-b7b2-4e0002eb5b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>3188a7e2-e8e9-4c01-9761-3ee0cb985fa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-ec7312ce8d7e61d5e725df17ccda207b</value>
      <webElementGuid>222259c5-00ac-4ca1-913f-a0afb3b0df13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'txtDateEnd']</value>
      <webElementGuid>0bc973d6-4d30-4aab-91dc-5f8eafdfac79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'txtDateEnd']</value>
      <webElementGuid>4bd409c0-de45-4032-ab93-8513715aefca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtDateEnd' and @type = 'text']</value>
      <webElementGuid>339da282-5352-482f-afd4-c634cc5dcb1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
