<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_IsNonDefinitive</name>
   <tag></tag>
   <elementGuidId>553bf08e-a608-48b2-93c6-92a2bace2158</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;IsNonDefinitive&quot;]#IsNonDefinitive[value=&quot;True&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[(@name = 'IsNonDefinitive') and (@id = 'IsNonDefinitive') and (@value = 'True')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#IsNonDefinitive >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c7a92bb-29e2-42f8-a9d1-f1663848656c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>cc194d5e-cee1-4e9a-af03-1a86f0586be3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>7601f36f-d3b2-489b-be5a-ed22502ef0b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>3c6efcc3-6505-49b7-89c8-f50ea854aa44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IsNonDefinitive</value>
      <webElementGuid>92e17dc5-b2d5-460a-9294-0e120475cb98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IsNonDefinitive</value>
      <webElementGuid>3f8aae1c-c591-4b10-8e60-9fdb59b6e2a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-c189cf15a36e89804980217ff3038f64</value>
      <webElementGuid>0ff716f9-bff1-427b-aa82-37e819251988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@name = 'IsNonDefinitive') and (@id = 'IsNonDefinitive') and (@value = 'True')]</value>
      <webElementGuid>7d6cb504-c5b1-44d4-8664-22acdb83d009</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@name = 'IsNonDefinitive') and (@id = 'IsNonDefinitive') and (@value = 'True')]</value>
      <webElementGuid>f97f3a72-f2ff-4649-98c7-a9ea31392644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'IsNonDefinitive' and @id = 'IsNonDefinitive']</value>
      <webElementGuid>bdff3a23-a76b-4245-a078-d90109fcffda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
