<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_txtDateStart</name>
   <tag></tag>
   <elementGuidId>a651da97-5456-4e48-b6ef-0ce33674c755</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtDateStart</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'txtDateStart']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtDateStart</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>985be950-dba4-4794-945c-918ec23e0cdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtDateStart</value>
      <webElementGuid>735b9eff-b515-4c75-b0ef-d0a17faa2b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control custom-bckgrndclrwht hasDatepicker</value>
      <webElementGuid>c881a04b-df00-4dc4-9afc-c864bee6833d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1b4438fb-d9a3-4858-a8f8-1b6e1bec61c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>c7a639fb-5a66-44ca-9e01-0ceb21f61637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-16c4f55074e7e5b99d06f9a57a7d9295</value>
      <webElementGuid>167cd8c0-2a49-4222-918b-91c5e90d7337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'txtDateStart']</value>
      <webElementGuid>b96a721d-a063-4ffc-84f4-06db59403d0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'txtDateStart']</value>
      <webElementGuid>c5d5a08a-652a-4f6d-842d-3f8fbe5453d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtDateStart' and @type = 'text']</value>
      <webElementGuid>d485f1fe-a5c8-4cbd-8d5b-0a09505a8c8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
