<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Inputter_1</name>
   <tag></tag>
   <elementGuidId>ace9e373-8086-4ab5-98f6-61e73726b2c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[role=&quot;option&quot;]:nth-child(4)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[(@role = 'option') and (position() = 4)]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'select2-RoleId-result-ka56-16' and (text() = 'Admin Unit &amp; Wilayah' or . = 'Admin Unit &amp; Wilayah')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Admin Unit &amp; Wilayah&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>e576fe6f-cbe4-4578-a133-0ebaeff2432e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option</value>
      <webElementGuid>b4c592fa-0f59-46e9-8c55-8c8c0bac06dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-RoleId-result-ka56-16</value>
      <webElementGuid>ff84dc3b-5b2d-4879-87d0-99523354c9eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>782876f6-3b3e-4f3a-a127-25c9863d36ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>988903f2-63e1-44f6-9dc2-df8d28bbdc5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-RoleId-result-ka56-16</value>
      <webElementGuid>36f203a5-12f3-45d2-8c52-42b3fa789169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Admin Unit &amp; Wilayah</value>
      <webElementGuid>a657361b-5e91-47cd-a7a8-8d3440662340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a2fc4237b447912142f8e47f1e5d0571</value>
      <webElementGuid>7c8e1e68-c5dc-43f4-86cf-0dde7649df7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@role = 'option') and (position() = 4)]</value>
      <webElementGuid>8e54a84d-fc45-4679-bda4-b35891dde419</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@role = 'option') and (position() = 4)]</value>
      <webElementGuid>87400ada-e6c4-47c8-be7a-b28d18992c41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-RoleId-result-ka56-16' and (text() = 'Admin Unit &amp; Wilayah' or . = 'Admin Unit &amp; Wilayah')]</value>
      <webElementGuid>fc140967-1154-48a5-ba77-3cf2e41443b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
