<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_KKLK Kantor Pusat</name>
   <tag></tag>
   <elementGuidId>dd160c47-c5a3-40fe-87f9-1fa7bc9aab90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[role=&quot;option&quot;]:nth-child(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[(@role = 'option') and (position() = 2)]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'KKLK Kantor Pusat' or . = 'KKLK Kantor Pusat')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;KKLK Kantor Pusat&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>954e8bd6-29ba-4395-9647-71c740db0a8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>3a4120fa-c35b-42da-9e12-936cc3657875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>93b2dbd9-d0c8-4bd1-abb9-01b38228c4aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>71989017-e3c1-440e-b2a3-c32d02bf8e92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>583</value>
      <webElementGuid>5062593d-a339-4c34-87bc-7fa7b0273256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KKLK Kantor Pusat</value>
      <webElementGuid>f3f61d68-e688-4e4e-870c-d81776f930bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-7cea6358c17f3fcafe32e993a1ac5a3f</value>
      <webElementGuid>81ae0472-df24-4047-8407-27eac96d214c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@role = 'option') and (position() = 2)]</value>
      <webElementGuid>ea699210-aceb-4f64-a305-8661da5cbd56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@role = 'option') and (position() = 2)]</value>
      <webElementGuid>05db4d57-43d7-47c1-89fa-6f01febea61c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'KKLK Kantor Pusat' or . = 'KKLK Kantor Pusat')]</value>
      <webElementGuid>17ec4889-e3e8-49a5-87bd-ee2cb0d67e96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
