<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_KKLK - SME</name>
   <tag></tag>
   <elementGuidId>d07a5976-bc57-4d1f-85e2-478ccd0ff4fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[role=&quot;option&quot;]:nth-child(1)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[(@role = 'option') and (position() = 1)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;KKLK - SME&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>f7d3ee2d-9ee1-42ae-9003-e754fa7d8e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>e0aa13f5-26ef-44da-95bc-67f4b2c4369e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>040c9ad7-79f9-4078-879b-9a8a28c1793f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8e5a859f-c0f5-4102-828e-d77bac743524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>720</value>
      <webElementGuid>bd6b456f-516a-43b9-a128-11d36881aa92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KKLK - SME</value>
      <webElementGuid>0627d27a-f4b2-4090-9215-7c804f30844e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-b5a7388a68fb2b08bb910a353a5f5f6b</value>
      <webElementGuid>b3d10e3c-1961-4c0e-bdfb-342768d4952d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@role = 'option') and (position() = 1)]</value>
      <webElementGuid>b3fd8b4e-2486-4ea3-9d8a-4b865deaa1ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@role = 'option') and (position() = 1)]</value>
      <webElementGuid>9bcd5260-11bb-4cdd-86a3-2e36136f76cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'KKLK - SME' or . = 'KKLK - SME')]</value>
      <webElementGuid>8fe5dfef-c997-4f88-90e8-93826066c314</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
