<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_STA BENGKULU</name>
   <tag></tag>
   <elementGuidId>0005c571-2cd7-4c22-baad-cb9d44834787</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[role=&quot;option&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@role = 'option']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'STA BENGKULU' or . = 'STA BENGKULU')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;STA BENGKULU&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>0e52c0ab-e669-4185-a783-908474cbbb92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>b5a5559b-4d76-41a5-a8a3-655c4cb3a878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>fdcd89c5-8cf3-42a0-8e4f-da04645937eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4ea38d71-5bb1-49a8-b6be-c38e79b1d466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>158</value>
      <webElementGuid>8f55a0bb-f3d4-4836-b040-666090fdfe81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>STA BENGKULU</value>
      <webElementGuid>b1a3a07f-a343-4ea0-9446-93d56d95b7f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-aa05a2136210d9be8768266b332a2787</value>
      <webElementGuid>0e84bcb5-94fc-420c-bc9f-2f397ff0e911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@role = 'option']</value>
      <webElementGuid>96ac8e36-4ed5-4e70-9945-9b98529bb7e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@role = 'option']</value>
      <webElementGuid>c1d29631-0cba-48f5-b4fc-6b886aa4f0e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'STA BENGKULU' or . = 'STA BENGKULU')]</value>
      <webElementGuid>1aa46e0b-31d6-4382-9849-d77da6b7fc16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
