<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Beranda</name>
   <tag></tag>
   <elementGuidId>958f726e-68a1-4675-bab2-e7e20e6aec8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[href=&quot;\.\.\/Home\/Index&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@href = '../Home/Index']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Beranda&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>994f40a1-b777-4d10-9252-276bdfb76662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>../Home/Index</value>
      <webElementGuid>8f888702-830d-42ac-ba81-68d25f960e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link child-Menu active</value>
      <webElementGuid>4d3b256e-a63f-430e-ad82-550eb82b6bcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Beranda</value>
      <webElementGuid>f23ba994-e5a0-4dbc-8339-658e462536fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0b11deff3f651c94776e31c1f1a2aa2b</value>
      <webElementGuid>bddf422c-1ba6-4d7f-8a76-a9f914b322f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@href = '../Home/Index']</value>
      <webElementGuid>88b9e25a-1842-476f-ac06-716de52aad3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@href = '../Home/Index']</value>
      <webElementGuid>3b0550bb-371f-46fb-9b07-9f05eb5fd9ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '../Home/Index' and (text() = 'Beranda' or . = 'Beranda')]</value>
      <webElementGuid>e6102819-7d6e-4ea7-bdce-e715d9ca1cbf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
